/// Het Spaanse woordenboek: (Spaans, Nederlands, Engels).
///
/// De uitspraak wordt automatisch afgeleid (zie `pronounce.dart`), omdat
/// Spaans fonetisch regelmatig is — net als in een fysiek woordenboek staat
/// hier per woord alleen het lemma met de vertalingen.
library;

const List<(String, String, String)> kWordEntries = [
  // ── Getallen ──
  ('cero', 'nul', 'zero'),
  ('uno', 'één', 'one'),
  ('dos', 'twee', 'two'),
  ('tres', 'drie', 'three'),
  ('cuatro', 'vier', 'four'),
  ('cinco', 'vijf', 'five'),
  ('seis', 'zes', 'six'),
  ('siete', 'zeven', 'seven'),
  ('ocho', 'acht', 'eight'),
  ('nueve', 'negen', 'nine'),
  ('diez', 'tien', 'ten'),
  ('once', 'elf', 'eleven'),
  ('doce', 'twaalf', 'twelve'),
  ('trece', 'dertien', 'thirteen'),
  ('catorce', 'veertien', 'fourteen'),
  ('quince', 'vijftien', 'fifteen'),
  ('veinte', 'twintig', 'twenty'),
  ('treinta', 'dertig', 'thirty'),
  ('cuarenta', 'veertig', 'forty'),
  ('cincuenta', 'vijftig', 'fifty'),
  ('sesenta', 'zestig', 'sixty'),
  ('setenta', 'zeventig', 'seventy'),
  ('ochenta', 'tachtig', 'eighty'),
  ('noventa', 'negentig', 'ninety'),
  ('cien', 'honderd', 'hundred'),
  ('mil', 'duizend', 'thousand'),
  ('millón', 'miljoen', 'million'),
  ('primero', 'eerste', 'first'),
  ('segundo', 'tweede', 'second'),
  ('último', 'laatste', 'last'),
  // ── Dagen, maanden en seizoenen ──
  ('lunes', 'maandag', 'Monday'),
  ('martes', 'dinsdag', 'Tuesday'),
  ('miércoles', 'woensdag', 'Wednesday'),
  ('jueves', 'donderdag', 'Thursday'),
  ('viernes', 'vrijdag', 'Friday'),
  ('sábado', 'zaterdag', 'Saturday'),
  ('domingo', 'zondag', 'Sunday'),
  ('enero', 'januari', 'January'),
  ('febrero', 'februari', 'February'),
  ('marzo', 'maart', 'March'),
  ('abril', 'april', 'April'),
  ('mayo', 'mei', 'May'),
  ('junio', 'juni', 'June'),
  ('julio', 'juli', 'July'),
  ('agosto', 'augustus', 'August'),
  ('septiembre', 'september', 'September'),
  ('octubre', 'oktober', 'October'),
  ('noviembre', 'november', 'November'),
  ('diciembre', 'december', 'December'),
  ('primavera', 'lente', 'spring'),
  ('verano', 'zomer', 'summer'),
  ('otoño', 'herfst', 'autumn'),
  ('invierno', 'winter', 'winter'),
  // ── Tijd ──
  ('tiempo', 'tijd', 'time'),
  ('hora', 'uur', 'hour'),
  ('minuto', 'minuut', 'minute'),
  ('momento', 'moment', 'moment'),
  ('día', 'dag', 'day'),
  ('semana', 'week', 'week'),
  ('mes', 'maand', 'month'),
  ('año', 'jaar', 'year'),
  ('hoy', 'vandaag', 'today'),
  ('ayer', 'gisteren', 'yesterday'),
  ('mañana', 'morgen', 'tomorrow'),
  ('tarde', 'middag', 'afternoon'),
  ('noche', 'nacht', 'night'),
  ('mediodía', 'middaguur', 'noon'),
  ('medianoche', 'middernacht', 'midnight'),
  ('fecha', 'datum', 'date'),
  ('reloj', 'klok', 'clock'),
  ('calendario', 'kalender', 'calendar'),
  ('siglo', 'eeuw', 'century'),
  ('época', 'tijdperk', 'era'),
  ('pasado', 'verleden', 'past'),
  ('futuro', 'toekomst', 'future'),
  ('temprano', 'vroeg', 'early'),
  ('pronto', 'binnenkort', 'soon'),
  ('ahora', 'nu', 'now'),
  // ── Familie en mensen ──
  ('familia', 'familie', 'family'),
  ('padre', 'vader', 'father'),
  ('madre', 'moeder', 'mother'),
  ('hijo', 'zoon', 'son'),
  ('hija', 'dochter', 'daughter'),
  ('hermano', 'broer', 'brother'),
  ('hermana', 'zus', 'sister'),
  ('abuelo', 'opa', 'grandfather'),
  ('abuela', 'oma', 'grandmother'),
  ('tío', 'oom', 'uncle'),
  ('tía', 'tante', 'aunt'),
  ('primo', 'neef', 'cousin'),
  ('sobrino', 'neefje', 'nephew'),
  ('nieto', 'kleinzoon', 'grandson'),
  ('esposo', 'echtgenoot', 'husband'),
  ('esposa', 'echtgenote', 'wife'),
  ('marido', 'man (echtgenoot)', 'husband'),
  ('mujer', 'vrouw', 'woman'),
  ('hombre', 'man', 'man'),
  ('niño', 'kind (jongen)', 'child'),
  ('niña', 'meisje', 'girl'),
  ('bebé', 'baby', 'baby'),
  ('chico', 'jongen', 'boy'),
  ('chica', 'meid', 'girl'),
  ('joven', 'jongere', 'young person'),
  ('adulto', 'volwassene', 'adult'),
  ('persona', 'persoon', 'person'),
  ('gente', 'mensen', 'people'),
  ('amigo', 'vriend', 'friend'),
  ('amiga', 'vriendin', 'female friend'),
  ('vecino', 'buurman', 'neighbour'),
  ('señor', 'meneer', 'sir'),
  ('señora', 'mevrouw', 'madam'),
  ('nombre', 'naam', 'name'),
  ('apellido', 'achternaam', 'surname'),
  ('boda', 'bruiloft', 'wedding'),
  ('pareja', 'stel', 'couple'),
  ('novio', 'vriendje', 'boyfriend'),
  ('novia', 'vriendinnetje', 'girlfriend'),
  ('invitado', 'gast', 'guest'),
  // ── Lichaam ──
  ('cuerpo', 'lichaam', 'body'),
  ('cabeza', 'hoofd', 'head'),
  ('cara', 'gezicht', 'face'),
  ('ojo', 'oog', 'eye'),
  ('oreja', 'oor', 'ear'),
  ('nariz', 'neus', 'nose'),
  ('boca', 'mond', 'mouth'),
  ('diente', 'tand', 'tooth'),
  ('lengua', 'tong', 'tongue'),
  ('labio', 'lip', 'lip'),
  ('cuello', 'nek', 'neck'),
  ('hombro', 'schouder', 'shoulder'),
  ('brazo', 'arm', 'arm'),
  ('codo', 'elleboog', 'elbow'),
  ('mano', 'hand', 'hand'),
  ('dedo', 'vinger', 'finger'),
  ('uña', 'nagel', 'nail'),
  ('pecho', 'borst', 'chest'),
  ('espalda', 'rug', 'back'),
  ('corazón', 'hart', 'heart'),
  ('estómago', 'maag', 'stomach'),
  ('pierna', 'been', 'leg'),
  ('rodilla', 'knie', 'knee'),
  ('pie', 'voet', 'foot'),
  ('piel', 'huid', 'skin'),
  ('pelo', 'haar', 'hair'),
  ('sangre', 'bloed', 'blood'),
  ('hueso', 'bot', 'bone'),
  ('músculo', 'spier', 'muscle'),
  ('cerebro', 'brein', 'brain'),
  ('voz', 'stem', 'voice'),
  ('barba', 'baard', 'beard'),
  // ── Huis ──
  ('casa', 'huis', 'house'),
  ('hogar', 'thuis', 'home'),
  ('apartamento', 'appartement', 'apartment'),
  ('edificio', 'gebouw', 'building'),
  ('habitación', 'kamer', 'room'),
  ('dormitorio', 'slaapkamer', 'bedroom'),
  ('cocina', 'keuken', 'kitchen'),
  ('baño', 'badkamer', 'bathroom'),
  ('salón', 'woonkamer', 'living room'),
  ('comedor', 'eetkamer', 'dining room'),
  ('pared', 'muur', 'wall'),
  ('techo', 'plafond', 'ceiling'),
  ('suelo', 'vloer', 'floor'),
  ('escalera', 'trap', 'stairs'),
  ('puerta', 'deur', 'door'),
  ('ventana', 'raam', 'window'),
  ('llave', 'sleutel', 'key'),
  ('mesa', 'tafel', 'table'),
  ('silla', 'stoel', 'chair'),
  ('sillón', 'fauteuil', 'armchair'),
  ('sofá', 'bank', 'sofa'),
  ('cama', 'bed', 'bed'),
  ('almohada', 'kussen', 'pillow'),
  ('manta', 'deken', 'blanket'),
  ('armario', 'kast', 'wardrobe'),
  ('espejo', 'spiegel', 'mirror'),
  ('lámpara', 'lamp', 'lamp'),
  ('luz', 'licht', 'light'),
  ('cuadro', 'schilderij', 'painting'),
  ('alfombra', 'tapijt', 'carpet'),
  ('cortina', 'gordijn', 'curtain'),
  ('estantería', 'boekenkast', 'bookcase'),
  ('cajón', 'lade', 'drawer'),
  ('nevera', 'koelkast', 'fridge'),
  ('horno', 'oven', 'oven'),
  ('ducha', 'douche', 'shower'),
  ('jabón', 'zeep', 'soap'),
  ('toalla', 'handdoek', 'towel'),
  ('basura', 'afval', 'rubbish'),
  ('jardín', 'tuin', 'garden'),
  ('garaje', 'garage', 'garage'),
  ('balcón', 'balkon', 'balcony'),
  ('piscina', 'zwembad', 'swimming pool'),
  ('ascensor', 'lift', 'elevator'),
  ('buzón', 'brievenbus', 'letterbox'),
  // ── Eten en drinken ──
  ('comida', 'eten', 'food'),
  ('desayuno', 'ontbijt', 'breakfast'),
  ('almuerzo', 'lunch', 'lunch'),
  ('cena', 'avondeten', 'dinner'),
  ('hambre', 'honger', 'hunger'),
  ('sed', 'dorst', 'thirst'),
  ('plato', 'bord', 'plate'),
  ('vaso', 'glas', 'glass'),
  ('taza', 'kopje', 'cup'),
  ('botella', 'fles', 'bottle'),
  ('cuchillo', 'mes', 'knife'),
  ('tenedor', 'vork', 'fork'),
  ('cuchara', 'lepel', 'spoon'),
  ('servilleta', 'servet', 'napkin'),
  ('receta', 'recept', 'recipe'),
  ('ingrediente', 'ingrediënt', 'ingredient'),
  ('pan', 'brood', 'bread'),
  ('mantequilla', 'boter', 'butter'),
  ('queso', 'kaas', 'cheese'),
  ('huevo', 'ei', 'egg'),
  ('leche', 'melk', 'milk'),
  ('yogur', 'yoghurt', 'yoghurt'),
  ('arroz', 'rijst', 'rice'),
  ('pasta', 'pasta', 'pasta'),
  ('sopa', 'soep', 'soup'),
  ('ensalada', 'salade', 'salad'),
  ('carne', 'vlees', 'meat'),
  ('pollo', 'kip', 'chicken'),
  ('pescado', 'vis (gerecht)', 'fish'),
  ('jamón', 'ham', 'ham'),
  ('salchicha', 'worst', 'sausage'),
  ('verdura', 'groente', 'vegetable'),
  ('patata', 'aardappel', 'potato'),
  ('tomate', 'tomaat', 'tomato'),
  ('cebolla', 'ui', 'onion'),
  ('ajo', 'knoflook', 'garlic'),
  ('zanahoria', 'wortel', 'carrot'),
  ('lechuga', 'sla', 'lettuce'),
  ('fruta', 'fruit', 'fruit'),
  ('manzana', 'appel', 'apple'),
  ('naranja', 'sinaasappel', 'orange'),
  ('plátano', 'banaan', 'banana'),
  ('fresa', 'aardbei', 'strawberry'),
  ('uva', 'druif', 'grape'),
  ('limón', 'citroen', 'lemon'),
  ('melón', 'meloen', 'melon'),
  ('sandía', 'watermeloen', 'watermelon'),
  ('pera', 'peer', 'pear'),
  ('azúcar', 'suiker', 'sugar'),
  ('sal', 'zout', 'salt'),
  ('pimienta', 'peper', 'pepper'),
  ('aceite', 'olie', 'oil'),
  ('vinagre', 'azijn', 'vinegar'),
  ('salsa', 'saus', 'sauce'),
  ('postre', 'toetje', 'dessert'),
  ('pastel', 'taart', 'cake'),
  ('helado', 'ijsje', 'ice cream'),
  ('chocolate', 'chocolade', 'chocolate'),
  ('galleta', 'koekje', 'biscuit'),
  ('miel', 'honing', 'honey'),
  ('agua', 'water', 'water'),
  ('café', 'koffie', 'coffee'),
  ('té', 'thee', 'tea'),
  ('zumo', 'sap', 'juice'),
  ('vino', 'wijn', 'wine'),
  ('cerveza', 'bier', 'beer'),
  ('refresco', 'frisdrank', 'soft drink'),
  ('hielo', 'ijs', 'ice'),
  // ── Dieren ──
  ('animal', 'dier', 'animal'),
  ('perro', 'hond', 'dog'),
  ('gato', 'kat', 'cat'),
  ('pájaro', 'vogel', 'bird'),
  ('pez', 'vis', 'fish'),
  ('caballo', 'paard', 'horse'),
  ('vaca', 'koe', 'cow'),
  ('cerdo', 'varken', 'pig'),
  ('oveja', 'schaap', 'sheep'),
  ('cabra', 'geit', 'goat'),
  ('gallina', 'kip (hen)', 'hen'),
  ('gallo', 'haan', 'rooster'),
  ('pato', 'eend', 'duck'),
  ('conejo', 'konijn', 'rabbit'),
  ('ratón', 'muis', 'mouse'),
  ('león', 'leeuw', 'lion'),
  ('tigre', 'tijger', 'tiger'),
  ('elefante', 'olifant', 'elephant'),
  ('mono', 'aap', 'monkey'),
  ('oso', 'beer', 'bear'),
  ('lobo', 'wolf', 'wolf'),
  ('zorro', 'vos', 'fox'),
  ('ciervo', 'hert', 'deer'),
  ('serpiente', 'slang', 'snake'),
  ('araña', 'spin', 'spider'),
  ('mosca', 'vlieg', 'fly'),
  ('abeja', 'bij', 'bee'),
  ('mariposa', 'vlinder', 'butterfly'),
  ('hormiga', 'mier', 'ant'),
  ('tortuga', 'schildpad', 'turtle'),
  ('rana', 'kikker', 'frog'),
  ('ballena', 'walvis', 'whale'),
  ('delfín', 'dolfijn', 'dolphin'),
  ('tiburón', 'haai', 'shark'),
  ('águila', 'adelaar', 'eagle'),
  ('burro', 'ezel', 'donkey'),
  // ── Natuur en weer ──
  ('naturaleza', 'natuur', 'nature'),
  ('árbol', 'boom', 'tree'),
  ('flor', 'bloem', 'flower'),
  ('planta', 'plant', 'plant'),
  ('hierba', 'gras', 'grass'),
  ('hoja', 'blad', 'leaf'),
  ('raíz', 'wortel (plant)', 'root'),
  ('rama', 'tak', 'branch'),
  ('semilla', 'zaadje', 'seed'),
  ('bosque', 'bos', 'forest'),
  ('selva', 'oerwoud', 'jungle'),
  ('campo', 'platteland', 'countryside'),
  ('montaña', 'berg', 'mountain'),
  ('colina', 'heuvel', 'hill'),
  ('valle', 'vallei', 'valley'),
  ('río', 'rivier', 'river'),
  ('lago', 'meer', 'lake'),
  ('mar', 'zee', 'sea'),
  ('océano', 'oceaan', 'ocean'),
  ('ola', 'golf', 'wave'),
  ('playa', 'strand', 'beach'),
  ('arena', 'zand', 'sand'),
  ('isla', 'eiland', 'island'),
  ('desierto', 'woestijn', 'desert'),
  ('cielo', 'hemel', 'sky'),
  ('sol', 'zon', 'sun'),
  ('luna', 'maan', 'moon'),
  ('estrella', 'ster', 'star'),
  ('nube', 'wolk', 'cloud'),
  ('lluvia', 'regen', 'rain'),
  ('nieve', 'sneeuw', 'snow'),
  ('viento', 'wind', 'wind'),
  ('tormenta', 'storm', 'storm'),
  ('rayo', 'bliksem', 'lightning'),
  ('trueno', 'donder', 'thunder'),
  ('niebla', 'mist', 'fog'),
  ('arcoíris', 'regenboog', 'rainbow'),
  ('clima', 'klimaat', 'climate'),
  ('piedra', 'steen', 'stone'),
  ('roca', 'rots', 'rock'),
  ('tierra', 'aarde', 'earth'),
  ('fuego', 'vuur', 'fire'),
  ('humo', 'rook', 'smoke'),
  // ── Stad en plaatsen ──
  ('ciudad', 'stad', 'city'),
  ('pueblo', 'dorp', 'village'),
  ('barrio', 'wijk', 'neighbourhood'),
  ('calle', 'straat', 'street'),
  ('avenida', 'laan', 'avenue'),
  ('plaza', 'plein', 'square'),
  ('parque', 'park', 'park'),
  ('puente', 'brug', 'bridge'),
  ('esquina', 'hoek', 'corner'),
  ('iglesia', 'kerk', 'church'),
  ('catedral', 'kathedraal', 'cathedral'),
  ('castillo', 'kasteel', 'castle'),
  ('museo', 'museum', 'museum'),
  ('teatro', 'theater', 'theatre'),
  ('cine', 'bioscoop', 'cinema'),
  ('restaurante', 'restaurant', 'restaurant'),
  ('cafetería', 'café', 'coffee shop'),
  ('bar', 'kroeg', 'bar'),
  ('hotel', 'hotel', 'hotel'),
  ('tienda', 'winkel', 'shop'),
  ('mercado', 'markt', 'market'),
  ('supermercado', 'supermarkt', 'supermarket'),
  ('panadería', 'bakkerij', 'bakery'),
  ('carnicería', 'slagerij', 'butcher shop'),
  ('farmacia', 'apotheek', 'pharmacy'),
  ('hospital', 'ziekenhuis', 'hospital'),
  ('escuela', 'school', 'school'),
  ('universidad', 'universiteit', 'university'),
  ('biblioteca', 'bibliotheek', 'library'),
  ('oficina', 'kantoor', 'office'),
  ('banco', 'bank', 'bank'),
  ('correo', 'post', 'mail'),
  ('ayuntamiento', 'gemeentehuis', 'town hall'),
  ('comisaría', 'politiebureau', 'police station'),
  ('estadio', 'stadion', 'stadium'),
  ('gimnasio', 'sportschool', 'gym'),
  ('peluquería', 'kapper', 'hairdresser'),
  ('gasolinera', 'tankstation', 'petrol station'),
  ('aeropuerto', 'vliegveld', 'airport'),
  ('estación', 'station', 'station'),
  ('puerto', 'haven', 'port'),
  ('zoo', 'dierentuin', 'zoo'),
  // ── Reizen en vervoer ──
  ('viaje', 'reis', 'trip'),
  ('coche', 'auto', 'car'),
  ('autobús', 'bus', 'bus'),
  ('tren', 'trein', 'train'),
  ('avión', 'vliegtuig', 'airplane'),
  ('barco', 'boot', 'boat'),
  ('bicicleta', 'fiets', 'bicycle'),
  ('moto', 'motor', 'motorbike'),
  ('taxi', 'taxi', 'taxi'),
  ('metro', 'metro', 'underground'),
  ('camión', 'vrachtwagen', 'truck'),
  ('carretera', 'weg', 'road'),
  ('autopista', 'snelweg', 'motorway'),
  ('semáforo', 'stoplicht', 'traffic light'),
  ('mapa', 'kaart (land)', 'map'),
  ('maleta', 'koffer', 'suitcase'),
  ('mochila', 'rugzak', 'backpack'),
  ('pasaporte', 'paspoort', 'passport'),
  ('billete', 'kaartje', 'ticket'),
  ('entrada', 'ingang', 'entrance'),
  ('salida', 'uitgang', 'exit'),
  ('llegada', 'aankomst', 'arrival'),
  ('destino', 'bestemming', 'destination'),
  ('turista', 'toerist', 'tourist'),
  ('guía', 'gids', 'guide'),
  ('vacaciones', 'vakantie', 'holidays'),
  ('aventura', 'avontuur', 'adventure'),
  ('extranjero', 'buitenland', 'abroad'),
  ('frontera', 'grens', 'border'),
  ('aduana', 'douane', 'customs'),
  ('equipaje', 'bagage', 'luggage'),
  ('asiento', 'zitplaats', 'seat'),
  ('ventanilla', 'loket', 'counter window'),
  ('conductor', 'bestuurder', 'driver'),
  ('pasajero', 'passagier', 'passenger'),
  ('gasolina', 'benzine', 'petrol'),
  // ── Kleding ──
  ('ropa', 'kleding', 'clothes'),
  ('camisa', 'overhemd', 'shirt'),
  ('camiseta', 't-shirt', 't-shirt'),
  ('pantalón', 'broek', 'trousers'),
  ('falda', 'rok', 'skirt'),
  ('vestido', 'jurk', 'dress'),
  ('abrigo', 'jas', 'coat'),
  ('chaqueta', 'jasje', 'jacket'),
  ('jersey', 'trui', 'sweater'),
  ('traje', 'pak', 'suit'),
  ('corbata', 'stropdas', 'tie'),
  ('calcetín', 'sok', 'sock'),
  ('zapato', 'schoen', 'shoe'),
  ('bota', 'laars', 'boot'),
  ('zapatilla', 'sportschoen', 'trainer'),
  ('sombrero', 'hoed', 'hat'),
  ('gorra', 'pet', 'cap'),
  ('bufanda', 'sjaal', 'scarf'),
  ('guante', 'handschoen', 'glove'),
  ('cinturón', 'riem', 'belt'),
  ('bolsillo', 'zak (kleding)', 'pocket'),
  ('botón', 'knoop', 'button'),
  ('cremallera', 'rits', 'zip'),
  ('gafas', 'bril', 'glasses'),
  ('anillo', 'ring', 'ring'),
  ('collar', 'ketting', 'necklace'),
  ('pendiente', 'oorbel', 'earring'),
  ('paraguas', 'paraplu', 'umbrella'),
  ('pijama', 'pyjama', 'pyjamas'),
  ('bañador', 'zwembroek', 'swimsuit'),
  // ── Kleuren ──
  ('color', 'kleur', 'colour'),
  ('rojo', 'rood', 'red'),
  ('azul', 'blauw', 'blue'),
  ('verde', 'groen', 'green'),
  ('amarillo', 'geel', 'yellow'),
  ('negro', 'zwart', 'black'),
  ('blanco', 'wit', 'white'),
  ('gris', 'grijs', 'grey'),
  ('marrón', 'bruin', 'brown'),
  ('rosa', 'roze', 'pink'),
  ('morado', 'paars', 'purple'),
  ('dorado', 'goudkleurig', 'golden'),
  // ── School en werk ──
  ('clase', 'les', 'class'),
  ('aula', 'klaslokaal', 'classroom'),
  ('lección', 'les (leerstof)', 'lesson'),
  ('curso', 'cursus', 'course'),
  ('examen', 'examen', 'exam'),
  ('prueba', 'toets', 'test'),
  ('tarea', 'taak', 'task'),
  ('deberes', 'huiswerk', 'homework'),
  ('pregunta', 'vraag', 'question'),
  ('respuesta', 'antwoord', 'answer'),
  ('palabra', 'woord', 'word'),
  ('frase', 'zin', 'sentence'),
  ('texto', 'tekst', 'text'),
  ('página', 'pagina', 'page'),
  ('libro', 'boek', 'book'),
  ('cuaderno', 'schrift', 'notebook'),
  ('lápiz', 'potlood', 'pencil'),
  ('bolígrafo', 'pen', 'pen'),
  ('goma', 'gum', 'eraser'),
  ('regla', 'liniaal', 'ruler'),
  ('tijeras', 'schaar', 'scissors'),
  ('papel', 'papier', 'paper'),
  ('carta', 'brief', 'letter'),
  ('sello', 'postzegel', 'stamp'),
  ('idioma', 'taal', 'language'),
  ('gramática', 'grammatica', 'grammar'),
  ('vocabulario', 'woordenschat', 'vocabulary'),
  ('ejercicio', 'oefening', 'exercise'),
  ('error', 'fout', 'mistake'),
  ('nota', 'cijfer', 'grade'),
  ('diploma', 'diploma', 'diploma'),
  ('estudiante', 'student', 'student'),
  ('alumno', 'leerling', 'pupil'),
  ('profesor', 'docent', 'teacher'),
  ('maestro', 'leraar', 'schoolteacher'),
  ('director', 'directeur', 'director'),
  ('reunión', 'vergadering', 'meeting'),
  ('proyecto', 'project', 'project'),
  ('informe', 'verslag', 'report'),
  ('empresa', 'bedrijf', 'company'),
  ('jefe', 'baas', 'boss'),
  ('empleado', 'werknemer', 'employee'),
  ('sueldo', 'salaris', 'salary'),
  ('trabajo', 'werk', 'work'),
  // ── Beroepen ──
  ('médico', 'dokter', 'doctor'),
  ('enfermero', 'verpleegkundige', 'nurse'),
  ('dentista', 'tandarts', 'dentist'),
  ('abogado', 'advocaat', 'lawyer'),
  ('juez', 'rechter', 'judge'),
  ('policía', 'politieagent', 'police officer'),
  ('bombero', 'brandweerman', 'firefighter'),
  ('soldado', 'soldaat', 'soldier'),
  ('cocinero', 'kok', 'cook'),
  ('camarero', 'ober', 'waiter'),
  ('panadero', 'bakker', 'baker'),
  ('carnicero', 'slager', 'butcher'),
  ('peluquero', 'kapper (persoon)', 'hairdresser'),
  ('mecánico', 'monteur', 'mechanic'),
  ('electricista', 'elektricien', 'electrician'),
  ('carpintero', 'timmerman', 'carpenter'),
  ('pintor', 'schilder', 'painter'),
  ('escritor', 'schrijver', 'writer'),
  ('periodista', 'journalist', 'journalist'),
  ('actor', 'acteur', 'actor'),
  ('cantante', 'zanger', 'singer'),
  ('músico', 'muzikant', 'musician'),
  ('bailarín', 'danser', 'dancer'),
  ('deportista', 'sporter', 'athlete'),
  ('científico', 'wetenschapper', 'scientist'),
  ('ingeniero', 'ingenieur', 'engineer'),
  ('arquitecto', 'architect', 'architect'),
  ('agricultor', 'boer', 'farmer'),
  // ── Technologie en media ──
  ('teléfono', 'telefoon', 'telephone'),
  ('móvil', 'mobieltje', 'mobile phone'),
  ('ordenador', 'computer', 'computer'),
  ('pantalla', 'scherm', 'screen'),
  ('teclado', 'toetsenbord', 'keyboard'),
  ('internet', 'internet', 'internet'),
  ('red', 'netwerk', 'network'),
  ('mensaje', 'bericht', 'message'),
  ('foto', 'foto', 'photo'),
  ('cámara', 'camera', 'camera'),
  ('vídeo', 'video', 'video'),
  ('radio', 'radio', 'radio'),
  ('televisión', 'televisie', 'television'),
  ('película', 'film', 'film'),
  ('canal', 'kanaal', 'channel'),
  ('noticia', 'nieuwsbericht', 'news item'),
  ('aplicación', 'app', 'application'),
  ('juego', 'spel', 'game'),
  ('batería', 'batterij', 'battery'),
  ('cargador', 'oplader', 'charger'),
  ('auricular', 'koptelefoon', 'headphone'),
  ('impresora', 'printer', 'printer'),
  // ── Gezondheid ──
  ('salud', 'gezondheid', 'health'),
  ('enfermedad', 'ziekte', 'illness'),
  ('fiebre', 'koorts', 'fever'),
  ('gripe', 'griep', 'flu'),
  ('tos', 'hoest', 'cough'),
  ('dolor', 'pijn', 'pain'),
  ('herida', 'wond', 'wound'),
  ('medicina', 'medicijn', 'medicine'),
  ('pastilla', 'pil', 'pill'),
  ('cita', 'afspraak', 'appointment'),
  ('consulta', 'spreekuur', 'consultation'),
  ('urgencias', 'spoedeisende hulp', 'emergency room'),
  ('ambulancia', 'ambulance', 'ambulance'),
  ('seguro', 'verzekering', 'insurance'),
  ('dieta', 'dieet', 'diet'),
  ('descanso', 'rust', 'rest'),
  ('sueño', 'slaap', 'sleep'),
  ('energía', 'energie', 'energy'),
  ('fuerza', 'kracht', 'strength'),
  ('peso', 'gewicht', 'weight'),
  ('altura', 'lengte (hoogte)', 'height'),
  ('edad', 'leeftijd', 'age'),
  ('vida', 'leven', 'life'),
  ('muerte', 'dood', 'death'),
  // ── Sport en hobby ──
  ('deporte', 'sport', 'sport'),
  ('fútbol', 'voetbal', 'football'),
  ('baloncesto', 'basketbal', 'basketball'),
  ('tenis', 'tennis', 'tennis'),
  ('natación', 'zwemsport', 'swimming'),
  ('ciclismo', 'wielrennen', 'cycling'),
  ('atletismo', 'atletiek', 'athletics'),
  ('equipo', 'team', 'team'),
  ('partido', 'wedstrijd', 'match'),
  ('pelota', 'bal (klein)', 'ball'),
  ('balón', 'bal (groot)', 'ball'),
  ('gol', 'doelpunt', 'goal'),
  ('premio', 'prijs (beloning)', 'prize'),
  ('campeón', 'kampioen', 'champion'),
  ('carrera', 'race', 'race'),
  ('meta', 'finish', 'finish line'),
  ('afición', 'hobby', 'hobby'),
  ('pasatiempo', 'tijdverdrijf', 'pastime'),
  ('ajedrez', 'schaken', 'chess'),
  ('pesca', 'vissen (sport)', 'fishing'),
  ('caza', 'jacht', 'hunting'),
  ('senderismo', 'wandelsport', 'hiking'),
  ('camping', 'camping', 'camping'),
  ('esquí', 'skiën', 'skiing'),
  ('patinaje', 'schaatsen', 'skating'),
  ('yoga', 'yoga', 'yoga'),
  // ── Muziek en kunst ──
  ('música', 'muziek', 'music'),
  ('canción', 'lied', 'song'),
  ('ritmo', 'ritme', 'rhythm'),
  ('melodía', 'melodie', 'melody'),
  ('concierto', 'concert', 'concert'),
  ('guitarra', 'gitaar', 'guitar'),
  ('piano', 'piano', 'piano'),
  ('violín', 'viool', 'violin'),
  ('tambor', 'trommel', 'drum'),
  ('flauta', 'fluit', 'flute'),
  ('orquesta', 'orkest', 'orchestra'),
  ('arte', 'kunst', 'art'),
  ('pintura', 'schilderkunst', 'painting (art)'),
  ('dibujo', 'tekening', 'drawing'),
  ('escultura', 'beeldhouwwerk', 'sculpture'),
  ('poesía', 'poëzie', 'poetry'),
  ('poema', 'gedicht', 'poem'),
  ('novela', 'roman', 'novel'),
  ('cuento', 'verhaal', 'story'),
  ('escenario', 'podium', 'stage'),
  // ── Winkelen en geld ──
  ('dinero', 'geld', 'money'),
  ('precio', 'prijs (kosten)', 'price'),
  ('oferta', 'aanbieding', 'offer'),
  ('descuento', 'korting', 'discount'),
  ('rebajas', 'uitverkoop', 'sales'),
  ('caja', 'kassa', 'checkout'),
  ('tarjeta', 'kaart (pas)', 'card'),
  ('moneda', 'munt', 'coin'),
  ('cambio', 'wisselgeld', 'change'),
  ('cuenta', 'rekening', 'bill'),
  ('factura', 'factuur', 'invoice'),
  ('recibo', 'bonnetje', 'receipt'),
  ('regalo', 'cadeau', 'present'),
  ('compra', 'aankoop', 'purchase'),
  ('venta', 'verkoop', 'sale'),
  ('cliente', 'klant', 'customer'),
  ('cesta', 'mandje', 'basket'),
  ('carrito', 'winkelwagen', 'trolley'),
  ('marca', 'merk', 'brand'),
  ('talla', 'maat', 'size'),
  ('calidad', 'kwaliteit', 'quality'),
  ('euro', 'euro', 'euro'),
  // ── Gevoelens en abstracte begrippen ──
  ('amor', 'liefde', 'love'),
  ('odio', 'haat', 'hate'),
  ('miedo', 'angst', 'fear'),
  ('alegría', 'vreugde', 'joy'),
  ('tristeza', 'verdriet', 'sadness'),
  ('sorpresa', 'verrassing', 'surprise'),
  ('esperanza', 'hoop', 'hope'),
  ('deseo', 'wens', 'wish'),
  ('beso', 'kus', 'kiss'),
  ('abrazo', 'knuffel', 'hug'),
  ('sonrisa', 'glimlach', 'smile'),
  ('risa', 'lach', 'laughter'),
  ('lágrima', 'traan', 'tear'),
  ('problema', 'probleem', 'problem'),
  ('solución', 'oplossing', 'solution'),
  ('idea', 'idee', 'idea'),
  ('pensamiento', 'gedachte', 'thought'),
  ('memoria', 'geheugen', 'memory'),
  ('recuerdo', 'herinnering', 'memory (recollection)'),
  ('verdad', 'waarheid', 'truth'),
  ('mentira', 'leugen', 'lie'),
  ('secreto', 'geheim', 'secret'),
  ('historia', 'geschiedenis', 'history'),
  ('suerte', 'geluk (mazzel)', 'luck'),
  ('paz', 'vrede', 'peace'),
  ('guerra', 'oorlog', 'war'),
  ('libertad', 'vrijheid', 'freedom'),
  ('justicia', 'rechtvaardigheid', 'justice'),
  ('ley', 'wet', 'law'),
  ('cultura', 'cultuur', 'culture'),
  // ── Bijvoeglijke naamwoorden ──
  ('grande', 'groot', 'big'),
  ('pequeño', 'klein', 'small'),
  ('alto', 'lang (persoon)', 'tall'),
  ('bajo', 'kort (persoon)', 'short (height)'),
  ('largo', 'lang', 'long'),
  ('corto', 'kort', 'short'),
  ('ancho', 'breed', 'wide'),
  ('estrecho', 'smal', 'narrow'),
  ('gordo', 'dik', 'fat'),
  ('delgado', 'dun', 'thin'),
  ('fuerte', 'sterk', 'strong'),
  ('débil', 'zwak', 'weak'),
  ('rápido', 'snel', 'fast'),
  ('lento', 'langzaam', 'slow'),
  ('nuevo', 'nieuw', 'new'),
  ('viejo', 'oud', 'old'),
  ('bueno', 'goed', 'good'),
  ('malo', 'slecht', 'bad'),
  ('mejor', 'beter', 'better'),
  ('peor', 'slechter', 'worse'),
  ('bonito', 'mooi', 'pretty'),
  ('feo', 'lelijk', 'ugly'),
  ('hermoso', 'prachtig', 'beautiful'),
  ('guapo', 'knap', 'handsome'),
  ('limpio', 'schoon', 'clean'),
  ('sucio', 'vies', 'dirty'),
  ('lleno', 'vol', 'full'),
  ('vacío', 'leeg', 'empty'),
  ('abierto', 'open', 'open'),
  ('cerrado', 'gesloten', 'closed'),
  ('caliente', 'heet', 'hot'),
  ('frío', 'koud', 'cold'),
  ('caro', 'duur', 'expensive'),
  ('barato', 'goedkoop', 'cheap'),
  ('rico', 'rijk', 'rich'),
  ('pobre', 'arm', 'poor'),
  ('fácil', 'makkelijk', 'easy'),
  ('difícil', 'moeilijk', 'difficult'),
  ('feliz', 'gelukkig', 'happy'),
  ('triste', 'verdrietig', 'sad'),
  ('contento', 'blij', 'glad'),
  ('enfadado', 'boos', 'angry'),
  ('cansado', 'moe', 'tired'),
  ('enfermo', 'ziek', 'ill'),
  ('sano', 'gezond', 'healthy'),
  ('vivo', 'levend', 'alive'),
  ('muerto', 'dood (bn.)', 'dead'),
  ('ocupado', 'bezet', 'busy'),
  ('libre', 'vrij', 'free'),
  ('tranquilo', 'rustig', 'calm'),
  ('nervioso', 'zenuwachtig', 'nervous'),
  ('valiente', 'dapper', 'brave'),
  ('tímido', 'verlegen', 'shy'),
  ('simpático', 'aardig', 'nice'),
  ('antipático', 'onaardig', 'unfriendly'),
  ('amable', 'vriendelijk', 'kind'),
  ('serio', 'serieus', 'serious'),
  ('divertido', 'leuk', 'fun'),
  ('aburrido', 'saai', 'boring'),
  ('interesante', 'interessant', 'interesting'),
  ('importante', 'belangrijk', 'important'),
  ('necesario', 'nodig', 'necessary'),
  ('posible', 'mogelijk', 'possible'),
  ('imposible', 'onmogelijk', 'impossible'),
  ('correcto', 'juist', 'correct'),
  ('falso', 'onjuist', 'false'),
  ('verdadero', 'waar', 'true'),
  ('igual', 'gelijk', 'equal'),
  ('diferente', 'verschillend', 'different'),
  ('similar', 'vergelijkbaar', 'similar'),
  ('extraño', 'vreemd', 'strange'),
  ('normal', 'normaal', 'normal'),
  ('especial', 'bijzonder', 'special'),
  ('famoso', 'beroemd', 'famous'),
  ('conocido', 'bekend', 'well-known'),
  ('peligroso', 'gevaarlijk', 'dangerous'),
  ('dulce', 'zoet', 'sweet'),
  ('amargo', 'bitter', 'bitter'),
  ('salado', 'zout (bn.)', 'salty'),
  ('picante', 'pittig', 'spicy'),
  ('suave', 'zacht', 'soft'),
  ('duro', 'hard', 'hard'),
  ('blando', 'week (zacht)', 'tender'),
  ('pesado', 'zwaar', 'heavy'),
  ('ligero', 'licht (gewicht)', 'light'),
  ('oscuro', 'donker', 'dark'),
  ('claro', 'helder', 'clear'),
  ('brillante', 'stralend', 'bright'),
  ('mojado', 'nat', 'wet'),
  ('seco', 'droog', 'dry'),
  ('listo', 'slim', 'clever'),
  ('tonto', 'dom', 'silly'),
  ('loco', 'gek', 'crazy'),
  ('sabio', 'wijs', 'wise'),
  // ── Werkwoorden ──
  ('ser', 'zijn', 'to be'),
  ('estar', 'zijn (toestand)', 'to be (state)'),
  ('tener', 'hebben', 'to have'),
  ('hacer', 'doen', 'to do'),
  ('poder', 'kunnen', 'to be able'),
  ('decir', 'zeggen', 'to say'),
  ('ir', 'gaan', 'to go'),
  ('ver', 'zien', 'to see'),
  ('dar', 'geven', 'to give'),
  ('saber', 'weten', 'to know'),
  ('querer', 'willen', 'to want'),
  ('llegar', 'aankomen', 'to arrive'),
  ('pasar', 'passeren', 'to pass'),
  ('deber', 'moeten', 'must'),
  ('poner', 'zetten', 'to put'),
  ('parecer', 'lijken', 'to seem'),
  ('quedar', 'overblijven', 'to remain'),
  ('creer', 'geloven', 'to believe'),
  ('hablar', 'spreken', 'to speak'),
  ('llevar', 'dragen', 'to carry'),
  ('dejar', 'laten', 'to let'),
  ('seguir', 'volgen', 'to follow'),
  ('encontrar', 'vinden', 'to find'),
  ('llamar', 'bellen', 'to call'),
  ('venir', 'komen', 'to come'),
  ('pensar', 'denken', 'to think'),
  ('salir', 'uitgaan', 'to go out'),
  ('volver', 'terugkeren', 'to return'),
  ('tomar', 'nemen', 'to take'),
  ('conocer', 'kennen', 'to know (someone)'),
  ('vivir', 'wonen', 'to live'),
  ('sentir', 'voelen', 'to feel'),
  ('mirar', 'kijken', 'to look'),
  ('contar', 'tellen', 'to count'),
  ('empezar', 'beginnen', 'to begin'),
  ('esperar', 'wachten', 'to wait'),
  ('buscar', 'zoeken', 'to search'),
  ('entrar', 'binnenkomen', 'to enter'),
  ('trabajar', 'werken', 'to work'),
  ('escribir', 'schrijven', 'to write'),
  ('perder', 'verliezen', 'to lose'),
  ('entender', 'begrijpen', 'to understand'),
  ('pedir', 'vragen om', 'to ask for'),
  ('recibir', 'ontvangen', 'to receive'),
  ('recordar', 'zich herinneren', 'to remember'),
  ('terminar', 'eindigen', 'to finish'),
  ('permitir', 'toestaan', 'to allow'),
  ('aparecer', 'verschijnen', 'to appear'),
  ('conseguir', 'krijgen', 'to obtain'),
  ('comenzar', 'aanvangen', 'to commence'),
  ('servir', 'serveren', 'to serve'),
  ('sacar', 'eruit halen', 'to take out'),
  ('necesitar', 'nodig hebben', 'to need'),
  ('mantener', 'onderhouden', 'to maintain'),
  ('leer', 'lezen', 'to read'),
  ('caer', 'vallen', 'to fall'),
  ('cambiar', 'veranderen', 'to change'),
  ('crear', 'creëren', 'to create'),
  ('abrir', 'openen', 'to open'),
  ('oír', 'horen', 'to hear'),
  ('acabar', 'afmaken', 'to end'),
  ('ganar', 'winnen', 'to win'),
  ('formar', 'vormen', 'to form'),
  ('traer', 'meebrengen', 'to bring'),
  ('morir', 'sterven', 'to die'),
  ('aceptar', 'accepteren', 'to accept'),
  ('suponer', 'veronderstellen', 'to suppose'),
  ('comprender', 'snappen', 'to comprehend'),
  ('lograr', 'bereiken', 'to achieve'),
  ('explicar', 'uitleggen', 'to explain'),
  ('preguntar', 'vragen', 'to ask'),
  ('tocar', 'aanraken', 'to touch'),
  ('reconocer', 'herkennen', 'to recognise'),
  ('estudiar', 'studeren', 'to study'),
  ('nacer', 'geboren worden', 'to be born'),
  ('correr', 'rennen', 'to run'),
  ('utilizar', 'toepassen', 'to utilise'),
  ('pagar', 'betalen', 'to pay'),
  ('ayudar', 'helpen', 'to help'),
  ('gustar', 'leuk vinden', 'to like'),
  ('jugar', 'spelen', 'to play'),
  ('escuchar', 'luisteren', 'to listen'),
  ('ofrecer', 'aanbieden', 'to offer'),
  ('descubrir', 'ontdekken', 'to discover'),
  ('levantar', 'optillen', 'to lift'),
  ('intentar', 'proberen', 'to try'),
  ('usar', 'gebruiken', 'to use'),
  ('decidir', 'beslissen', 'to decide'),
  ('repetir', 'herhalen', 'to repeat'),
  ('olvidar', 'vergeten', 'to forget'),
  ('comer', 'eten (ww.)', 'to eat'),
  ('mostrar', 'tonen', 'to show'),
  ('mover', 'bewegen', 'to move'),
  ('continuar', 'doorgaan', 'to continue'),
  ('aprender', 'leren', 'to learn'),
  ('comprar', 'kopen', 'to buy'),
  ('subir', 'omhooggaan', 'to go up'),
  ('bajar', 'naar beneden gaan', 'to go down'),
  ('evitar', 'vermijden', 'to avoid'),
  ('cerrar', 'sluiten', 'to close'),
  ('responder', 'antwoorden', 'to answer'),
  ('sufrir', 'lijden', 'to suffer'),
  ('obtener', 'verkrijgen', 'to get'),
  ('observar', 'observeren', 'to observe'),
  ('imaginar', 'zich voorstellen', 'to imagine'),
  ('elegir', 'kiezen', 'to choose'),
  ('preparar', 'voorbereiden', 'to prepare'),
  ('proponer', 'voorstellen', 'to propose'),
  ('demostrar', 'aantonen', 'to demonstrate'),
  ('significar', 'betekenen', 'to mean'),
  ('reunir', 'verzamelen', 'to gather'),
  ('faltar', 'ontbreken', 'to lack'),
  ('acompañar', 'vergezellen', 'to accompany'),
  ('desear', 'wensen', 'to desire'),
  ('enseñar', 'onderwijzen', 'to teach'),
  ('construir', 'bouwen', 'to build'),
  ('vender', 'verkopen', 'to sell'),
  ('defender', 'verdedigen', 'to defend'),
  ('invitar', 'uitnodigen', 'to invite'),
  ('cantar', 'zingen', 'to sing'),
  ('bailar', 'dansen', 'to dance'),
  ('dormir', 'slapen', 'to sleep'),
  ('viajar', 'reizen', 'to travel'),
  ('nadar', 'zwemmen', 'to swim'),
  ('cocinar', 'koken', 'to cook'),
  ('limpiar', 'schoonmaken', 'to clean'),
  ('lavar', 'wassen', 'to wash'),
  ('romper', 'breken', 'to break'),
  ('reír', 'lachen', 'to laugh'),
  ('llorar', 'huilen', 'to cry'),
  ('besar', 'kussen (ww.)', 'to kiss'),
  ('abrazar', 'knuffelen', 'to hug'),
  ('saludar', 'begroeten', 'to greet'),
  ('caminar', 'wandelen', 'to walk'),
  ('andar', 'lopen', 'to stroll'),
  ('volar', 'vliegen', 'to fly'),
  ('conducir', 'autorijden', 'to drive'),
  ('montar', 'rijden op', 'to ride'),
  ('descansar', 'uitrusten', 'to rest'),
  ('despertar', 'wakker worden', 'to wake up'),
  ('celebrar', 'vieren', 'to celebrate'),
  ('felicitar', 'feliciteren', 'to congratulate'),
  ('regalar', 'cadeau geven', 'to gift'),
  ('apagar', 'uitzetten', 'to turn off'),
  ('encender', 'aanzetten', 'to turn on'),
  ('llenar', 'vullen', 'to fill'),
  ('guardar', 'bewaren', 'to keep'),
  ('enviar', 'versturen', 'to send'),
  ('beber', 'drinken', 'to drink'),
  ('soñar', 'dromen', 'to dream'),
  // ── Bijwoorden, voorzetsels en kleine woorden ──
  ('sí', 'ja', 'yes'),
  ('no', 'nee', 'no'),
  ('quizás', 'misschien', 'maybe'),
  ('también', 'ook', 'also'),
  ('tampoco', 'ook niet', 'neither'),
  ('siempre', 'altijd', 'always'),
  ('nunca', 'nooit', 'never'),
  ('luego', 'daarna', 'later'),
  ('después', 'na', 'after'),
  ('antes', 'voor (eerder)', 'before'),
  ('durante', 'tijdens', 'during'),
  ('mientras', 'terwijl', 'while'),
  ('ya', 'al', 'already'),
  ('todavía', 'nog', 'still'),
  ('aquí', 'hier', 'here'),
  ('allí', 'daar', 'there'),
  ('cerca', 'dichtbij', 'near'),
  ('lejos', 'ver weg', 'far'),
  ('arriba', 'boven', 'up'),
  ('abajo', 'beneden', 'down'),
  ('dentro', 'binnen', 'inside'),
  ('fuera', 'buiten', 'outside'),
  ('delante', 'vooraan', 'in front'),
  ('detrás', 'achter', 'behind'),
  ('encima', 'bovenop', 'on top'),
  ('debajo', 'onder', 'underneath'),
  ('entre', 'tussen', 'between'),
  ('junto', 'naast', 'next to'),
  ('alrededor', 'rondom', 'around'),
  ('muy', 'heel', 'very'),
  ('mucho', 'veel', 'much'),
  ('poco', 'weinig', 'little'),
  ('bastante', 'best wel', 'quite'),
  ('demasiado', 'te veel', 'too much'),
  ('casi', 'bijna', 'almost'),
  ('solo', 'alleen', 'only'),
  ('bien', 'goed (bw.)', 'well'),
  ('mal', 'slecht (bw.)', 'badly'),
  ('despacio', 'langzaam (bw.)', 'slowly'),
  ('además', 'bovendien', 'moreover'),
  ('entonces', 'toen', 'then'),
  ('pero', 'maar', 'but'),
  ('porque', 'omdat', 'because'),
  ('aunque', 'hoewel', 'although'),
  ('cuando', 'wanneer', 'when'),
  ('donde', 'waar', 'where'),
  ('como', 'zoals', 'like (as)'),
  ('qué', 'wat', 'what'),
  ('quién', 'wie', 'who'),
  ('cuál', 'welke', 'which'),
  ('cuánto', 'hoeveel', 'how much'),
  ('nada', 'niets', 'nothing'),
  ('algo', 'iets', 'something'),
  ('todo', 'alles', 'everything'),
  ('nadie', 'niemand', 'nobody'),
  ('alguien', 'iemand', 'somebody'),
  ('cada', 'elke', 'each'),
  ('otro', 'ander', 'other'),
  ('mismo', 'zelfde', 'same'),
  ('este', 'deze', 'this'),
  ('ese', 'die', 'that'),
  ('aquel', 'gindse', 'that (over there)'),
  ('con', 'met', 'with'),
  ('sin', 'zonder', 'without'),
  ('para', 'voor (bestemd)', 'for'),
  ('por', 'door', 'by'),
  ('sobre', 'over', 'about'),
  ('hasta', 'tot', 'until'),
  ('desde', 'vanaf', 'from'),
  ('hacia', 'naar', 'towards'),
  ('contra', 'tegen', 'against'),
  ('según', 'volgens', 'according to'),
  ('gracias', 'dank je', 'thank you'),
  ('hola', 'hallo', 'hello'),
  ('adiós', 'tot ziens', 'goodbye'),
  ('perdón', 'sorry', 'sorry'),
  ('bienvenido', 'welkom', 'welcome'),
];
