/// Het Spaanse woordenboek: (Spaans, Nederlands, Engels).
///
/// De uitspraak wordt automatisch afgeleid (zie `pronounce.dart`), omdat
/// Spaans fonetisch regelmatig is — net als in een fysiek woordenboek staat
/// hier per woord alleen het lemma met de vertalingen.
///
/// Uitbreiden kan met: `dart run tool/import_words.dart bestand.csv`
library;

const List<(String, String, String)> kWordEntries = [
  ('cero', 'nul', 'zero'),
  ('uno', 'één', 'one'),
  ('dos', 'twee', 'two'),
  ('tres', 'drie', 'three'),
  ('cuatro', 'vier', 'four'),
  ('cinco', 'vijf', 'five'),
  ('seis', 'zes', 'six'),
  ('siete', 'zeven', 'seven'),
  ('ocho', 'acht', 'eight'),
  ('nueve', 'negen', 'nine'),
  ('diez', 'tien', 'ten'),
  ('once', 'elf', 'eleven'),
  ('doce', 'twaalf', 'twelve'),
  ('trece', 'dertien', 'thirteen'),
  ('catorce', 'veertien', 'fourteen'),
  ('quince', 'vijftien', 'fifteen'),
  ('veinte', 'twintig', 'twenty'),
  ('treinta', 'dertig', 'thirty'),
  ('cuarenta', 'veertig', 'forty'),
  ('cincuenta', 'vijftig', 'fifty'),
  ('sesenta', 'zestig', 'sixty'),
  ('setenta', 'zeventig', 'seventy'),
  ('ochenta', 'tachtig', 'eighty'),
  ('noventa', 'negentig', 'ninety'),
  ('cien', 'honderd', 'hundred'),
  ('mil', 'duizend', 'thousand'),
  ('millón', 'miljoen', 'million'),
  ('primero', 'eerste', 'first'),
  ('segundo', 'tweede', 'second'),
  ('último', 'laatste', 'last'),
  ('lunes', 'maandag', 'Monday'),
  ('martes', 'dinsdag', 'Tuesday'),
  ('miércoles', 'woensdag', 'Wednesday'),
  ('jueves', 'donderdag', 'Thursday'),
  ('viernes', 'vrijdag', 'Friday'),
  ('sábado', 'zaterdag', 'Saturday'),
  ('domingo', 'zondag', 'Sunday'),
  ('enero', 'januari', 'January'),
  ('febrero', 'februari', 'February'),
  ('marzo', 'maart', 'March'),
  ('abril', 'april', 'April'),
  ('mayo', 'mei', 'May'),
  ('junio', 'juni', 'June'),
  ('julio', 'juli', 'July'),
  ('agosto', 'augustus', 'August'),
  ('septiembre', 'september', 'September'),
  ('octubre', 'oktober', 'October'),
  ('noviembre', 'november', 'November'),
  ('diciembre', 'december', 'December'),
  ('primavera', 'lente', 'spring'),
  ('verano', 'zomer', 'summer'),
  ('otoño', 'herfst', 'autumn'),
  ('invierno', 'winter', 'winter'),
  ('tiempo', 'tijd', 'time'),
  ('hora', 'uur', 'hour'),
  ('minuto', 'minuut', 'minute'),
  ('momento', 'moment', 'moment'),
  ('día', 'dag', 'day'),
  ('semana', 'week', 'week'),
  ('mes', 'maand', 'month'),
  ('año', 'jaar', 'year'),
  ('hoy', 'vandaag', 'today'),
  ('ayer', 'gisteren', 'yesterday'),
  ('mañana', 'morgen', 'tomorrow'),
  ('tarde', 'middag', 'afternoon'),
  ('noche', 'nacht', 'night'),
  ('mediodía', 'middaguur', 'noon'),
  ('medianoche', 'middernacht', 'midnight'),
  ('fecha', 'datum', 'date'),
  ('reloj', 'klok', 'clock'),
  ('calendario', 'kalender', 'calendar'),
  ('siglo', 'eeuw', 'century'),
  ('época', 'tijdperk', 'era'),
  ('pasado', 'verleden', 'past'),
  ('futuro', 'toekomst', 'future'),
  ('temprano', 'vroeg', 'early'),
  ('pronto', 'binnenkort', 'soon'),
  ('ahora', 'nu', 'now'),
  ('familia', 'familie', 'family'),
  ('padre', 'vader', 'father'),
  ('madre', 'moeder', 'mother'),
  ('hijo', 'zoon', 'son'),
  ('hija', 'dochter', 'daughter'),
  ('hermano', 'broer', 'brother'),
  ('hermana', 'zus', 'sister'),
  ('abuelo', 'opa', 'grandfather'),
  ('abuela', 'oma', 'grandmother'),
  ('tío', 'oom', 'uncle'),
  ('tía', 'tante', 'aunt'),
  ('primo', 'neef', 'cousin'),
  ('sobrino', 'neefje', 'nephew'),
  ('nieto', 'kleinzoon', 'grandson'),
  ('esposo', 'echtgenoot', 'husband'),
  ('esposa', 'echtgenote', 'wife'),
  ('marido', 'man (echtgenoot)', 'husband'),
  ('mujer', 'vrouw', 'woman'),
  ('hombre', 'man', 'man'),
  ('niño', 'kind (jongen)', 'child'),
  ('niña', 'meisje', 'girl'),
  ('bebé', 'baby', 'baby'),
  ('chico', 'jongen', 'boy'),
  ('chica', 'meid', 'girl'),
  ('joven', 'jongere', 'young person'),
  ('adulto', 'volwassene', 'adult'),
  ('persona', 'persoon', 'person'),
  ('gente', 'mensen', 'people'),
  ('amigo', 'vriend', 'friend'),
  ('amiga', 'vriendin', 'female friend'),
  ('vecino', 'buurman', 'neighbour'),
  ('señor', 'meneer', 'sir'),
  ('señora', 'mevrouw', 'madam'),
  ('nombre', 'naam', 'name'),
  ('apellido', 'achternaam', 'surname'),
  ('boda', 'bruiloft', 'wedding'),
  ('pareja', 'stel', 'couple'),
  ('novio', 'vriendje', 'boyfriend'),
  ('novia', 'vriendinnetje', 'girlfriend'),
  ('invitado', 'gast', 'guest'),
  ('cuerpo', 'lichaam', 'body'),
  ('cabeza', 'hoofd', 'head'),
  ('cara', 'gezicht', 'face'),
  ('ojo', 'oog', 'eye'),
  ('oreja', 'oor', 'ear'),
  ('nariz', 'neus', 'nose'),
  ('boca', 'mond', 'mouth'),
  ('diente', 'tand', 'tooth'),
  ('lengua', 'tong', 'tongue'),
  ('labio', 'lip', 'lip'),
  ('cuello', 'nek', 'neck'),
  ('hombro', 'schouder', 'shoulder'),
  ('brazo', 'arm', 'arm'),
  ('codo', 'elleboog', 'elbow'),
  ('mano', 'hand', 'hand'),
  ('dedo', 'vinger', 'finger'),
  ('uña', 'nagel', 'nail'),
  ('pecho', 'borst', 'chest'),
  ('espalda', 'rug', 'back'),
  ('corazón', 'hart', 'heart'),
  ('estómago', 'maag', 'stomach'),
  ('pierna', 'been', 'leg'),
  ('rodilla', 'knie', 'knee'),
  ('pie', 'voet', 'foot'),
  ('piel', 'huid', 'skin'),
  ('pelo', 'haar', 'hair'),
  ('sangre', 'bloed', 'blood'),
  ('hueso', 'bot', 'bone'),
  ('músculo', 'spier', 'muscle'),
  ('cerebro', 'brein', 'brain'),
  ('voz', 'stem', 'voice'),
  ('barba', 'baard', 'beard'),
  ('casa', 'huis', 'house'),
  ('hogar', 'thuis', 'home'),
  ('apartamento', 'appartement', 'apartment'),
  ('edificio', 'gebouw', 'building'),
  ('habitación', 'kamer', 'room'),
  ('dormitorio', 'slaapkamer', 'bedroom'),
  ('cocina', 'keuken', 'kitchen'),
  ('baño', 'badkamer', 'bathroom'),
  ('salón', 'woonkamer', 'living room'),
  ('comedor', 'eetkamer', 'dining room'),
  ('pared', 'muur', 'wall'),
  ('techo', 'plafond', 'ceiling'),
  ('suelo', 'vloer', 'floor'),
  ('escalera', 'trap', 'stairs'),
  ('puerta', 'deur', 'door'),
  ('ventana', 'raam', 'window'),
  ('llave', 'sleutel', 'key'),
  ('mesa', 'tafel', 'table'),
  ('silla', 'stoel', 'chair'),
  ('sillón', 'fauteuil', 'armchair'),
  ('sofá', 'bank', 'sofa'),
  ('cama', 'bed', 'bed'),
  ('almohada', 'kussen', 'pillow'),
  ('manta', 'deken', 'blanket'),
  ('armario', 'kast', 'wardrobe'),
  ('espejo', 'spiegel', 'mirror'),
  ('lámpara', 'lamp', 'lamp'),
  ('luz', 'licht', 'light'),
  ('cuadro', 'schilderij', 'painting'),
  ('alfombra', 'tapijt', 'carpet'),
  ('cortina', 'gordijn', 'curtain'),
  ('estantería', 'boekenkast', 'bookcase'),
  ('cajón', 'lade', 'drawer'),
  ('nevera', 'koelkast', 'fridge'),
  ('horno', 'oven', 'oven'),
  ('ducha', 'douche', 'shower'),
  ('jabón', 'zeep', 'soap'),
  ('toalla', 'handdoek', 'towel'),
  ('basura', 'afval', 'rubbish'),
  ('jardín', 'tuin', 'garden'),
  ('garaje', 'garage', 'garage'),
  ('balcón', 'balkon', 'balcony'),
  ('piscina', 'zwembad', 'swimming pool'),
  ('ascensor', 'lift', 'elevator'),
  ('buzón', 'brievenbus', 'letterbox'),
  ('comida', 'eten', 'food'),
  ('desayuno', 'ontbijt', 'breakfast'),
  ('almuerzo', 'lunch', 'lunch'),
  ('cena', 'avondeten', 'dinner'),
  ('hambre', 'honger', 'hunger'),
  ('sed', 'dorst', 'thirst'),
  ('plato', 'bord', 'plate'),
  ('vaso', 'glas', 'glass'),
  ('taza', 'kopje', 'cup'),
  ('botella', 'fles', 'bottle'),
  ('cuchillo', 'mes', 'knife'),
  ('tenedor', 'vork', 'fork'),
  ('cuchara', 'lepel', 'spoon'),
  ('servilleta', 'servet', 'napkin'),
  ('receta', 'recept', 'recipe'),
  ('ingrediente', 'ingrediënt', 'ingredient'),
  ('pan', 'brood', 'bread'),
  ('mantequilla', 'boter', 'butter'),
  ('queso', 'kaas', 'cheese'),
  ('huevo', 'ei', 'egg'),
  ('leche', 'melk', 'milk'),
  ('yogur', 'yoghurt', 'yoghurt'),
  ('arroz', 'rijst', 'rice'),
  ('pasta', 'pasta', 'pasta'),
  ('sopa', 'soep', 'soup'),
  ('ensalada', 'salade', 'salad'),
  ('carne', 'vlees', 'meat'),
  ('pollo', 'kip', 'chicken'),
  ('pescado', 'vis (gerecht)', 'fish'),
  ('jamón', 'ham', 'ham'),
  ('salchicha', 'worst', 'sausage'),
  ('verdura', 'groente', 'vegetable'),
  ('patata', 'aardappel', 'potato'),
  ('tomate', 'tomaat', 'tomato'),
  ('cebolla', 'ui', 'onion'),
  ('ajo', 'knoflook', 'garlic'),
  ('zanahoria', 'wortel', 'carrot'),
  ('lechuga', 'sla', 'lettuce'),
  ('fruta', 'fruit', 'fruit'),
  ('manzana', 'appel', 'apple'),
  ('naranja', 'sinaasappel', 'orange'),
  ('plátano', 'banaan', 'banana'),
  ('fresa', 'aardbei', 'strawberry'),
  ('uva', 'druif', 'grape'),
  ('limón', 'citroen', 'lemon'),
  ('melón', 'meloen', 'melon'),
  ('sandía', 'watermeloen', 'watermelon'),
  ('pera', 'peer', 'pear'),
  ('azúcar', 'suiker', 'sugar'),
  ('sal', 'zout', 'salt'),
  ('pimienta', 'peper', 'pepper'),
  ('aceite', 'olie', 'oil'),
  ('vinagre', 'azijn', 'vinegar'),
  ('salsa', 'saus', 'sauce'),
  ('postre', 'toetje', 'dessert'),
  ('pastel', 'taart', 'cake'),
  ('helado', 'ijsje', 'ice cream'),
  ('chocolate', 'chocolade', 'chocolate'),
  ('galleta', 'koekje', 'biscuit'),
  ('miel', 'honing', 'honey'),
  ('agua', 'water', 'water'),
  ('café', 'koffie', 'coffee'),
  ('té', 'thee', 'tea'),
  ('zumo', 'sap', 'juice'),
  ('vino', 'wijn', 'wine'),
  ('cerveza', 'bier', 'beer'),
  ('refresco', 'frisdrank', 'soft drink'),
  ('hielo', 'ijs', 'ice'),
  ('animal', 'dier', 'animal'),
  ('perro', 'hond', 'dog'),
  ('gato', 'kat', 'cat'),
  ('pájaro', 'vogel', 'bird'),
  ('pez', 'vis', 'fish'),
  ('caballo', 'paard', 'horse'),
  ('vaca', 'koe', 'cow'),
  ('cerdo', 'varken', 'pig'),
  ('oveja', 'schaap', 'sheep'),
  ('cabra', 'geit', 'goat'),
  ('gallina', 'kip (hen)', 'hen'),
  ('gallo', 'haan', 'rooster'),
  ('pato', 'eend', 'duck'),
  ('conejo', 'konijn', 'rabbit'),
  ('ratón', 'muis', 'mouse'),
  ('león', 'leeuw', 'lion'),
  ('tigre', 'tijger', 'tiger'),
  ('elefante', 'olifant', 'elephant'),
  ('mono', 'aap', 'monkey'),
  ('oso', 'beer', 'bear'),
  ('lobo', 'wolf', 'wolf'),
  ('zorro', 'vos', 'fox'),
  ('ciervo', 'hert', 'deer'),
  ('serpiente', 'slang', 'snake'),
  ('araña', 'spin', 'spider'),
  ('mosca', 'vlieg', 'fly'),
  ('abeja', 'bij', 'bee'),
  ('mariposa', 'vlinder', 'butterfly'),
  ('hormiga', 'mier', 'ant'),
  ('tortuga', 'schildpad', 'turtle'),
  ('rana', 'kikker', 'frog'),
  ('ballena', 'walvis', 'whale'),
  ('delfín', 'dolfijn', 'dolphin'),
  ('tiburón', 'haai', 'shark'),
  ('águila', 'adelaar', 'eagle'),
  ('burro', 'ezel', 'donkey'),
  ('naturaleza', 'natuur', 'nature'),
  ('árbol', 'boom', 'tree'),
  ('flor', 'bloem', 'flower'),
  ('planta', 'plant', 'plant'),
  ('hierba', 'gras', 'grass'),
  ('hoja', 'blad', 'leaf'),
  ('raíz', 'wortel (plant)', 'root'),
  ('rama', 'tak', 'branch'),
  ('semilla', 'zaadje', 'seed'),
  ('bosque', 'bos', 'forest'),
  ('selva', 'oerwoud', 'jungle'),
  ('campo', 'platteland', 'countryside'),
  ('montaña', 'berg', 'mountain'),
  ('colina', 'heuvel', 'hill'),
  ('valle', 'vallei', 'valley'),
  ('río', 'rivier', 'river'),
  ('lago', 'meer', 'lake'),
  ('mar', 'zee', 'sea'),
  ('océano', 'oceaan', 'ocean'),
  ('ola', 'golf', 'wave'),
  ('playa', 'strand', 'beach'),
  ('arena', 'zand', 'sand'),
  ('isla', 'eiland', 'island'),
  ('desierto', 'woestijn', 'desert'),
  ('cielo', 'hemel', 'sky'),
  ('sol', 'zon', 'sun'),
  ('luna', 'maan', 'moon'),
  ('estrella', 'ster', 'star'),
  ('nube', 'wolk', 'cloud'),
  ('lluvia', 'regen', 'rain'),
  ('nieve', 'sneeuw', 'snow'),
  ('viento', 'wind', 'wind'),
  ('tormenta', 'storm', 'storm'),
  ('rayo', 'bliksem', 'lightning'),
  ('trueno', 'donder', 'thunder'),
  ('niebla', 'mist', 'fog'),
  ('arcoíris', 'regenboog', 'rainbow'),
  ('clima', 'klimaat', 'climate'),
  ('piedra', 'steen', 'stone'),
  ('roca', 'rots', 'rock'),
  ('tierra', 'aarde', 'earth'),
  ('fuego', 'vuur', 'fire'),
  ('humo', 'rook', 'smoke'),
  ('ciudad', 'stad', 'city'),
  ('pueblo', 'dorp', 'village'),
  ('barrio', 'wijk', 'neighbourhood'),
  ('calle', 'straat', 'street'),
  ('avenida', 'laan', 'avenue'),
  ('plaza', 'plein', 'square'),
  ('parque', 'park', 'park'),
  ('puente', 'brug', 'bridge'),
  ('esquina', 'hoek', 'corner'),
  ('iglesia', 'kerk', 'church'),
  ('catedral', 'kathedraal', 'cathedral'),
  ('castillo', 'kasteel', 'castle'),
  ('museo', 'museum', 'museum'),
  ('teatro', 'theater', 'theatre'),
  ('cine', 'bioscoop', 'cinema'),
  ('restaurante', 'restaurant', 'restaurant'),
  ('cafetería', 'café', 'coffee shop'),
  ('bar', 'kroeg', 'bar'),
  ('hotel', 'hotel', 'hotel'),
  ('tienda', 'winkel', 'shop'),
  ('mercado', 'markt', 'market'),
  ('supermercado', 'supermarkt', 'supermarket'),
  ('panadería', 'bakkerij', 'bakery'),
  ('carnicería', 'slagerij', 'butcher shop'),
  ('farmacia', 'apotheek', 'pharmacy'),
  ('hospital', 'ziekenhuis', 'hospital'),
  ('escuela', 'school', 'school'),
  ('universidad', 'universiteit', 'university'),
  ('biblioteca', 'bibliotheek', 'library'),
  ('oficina', 'kantoor', 'office'),
  ('banco', 'bank', 'bank'),
  ('correo', 'post', 'mail'),
  ('ayuntamiento', 'gemeentehuis', 'town hall'),
  ('comisaría', 'politiebureau', 'police station'),
  ('estadio', 'stadion', 'stadium'),
  ('gimnasio', 'sportschool', 'gym'),
  ('peluquería', 'kapper', 'hairdresser'),
  ('gasolinera', 'tankstation', 'petrol station'),
  ('aeropuerto', 'vliegveld', 'airport'),
  ('estación', 'station', 'station'),
  ('puerto', 'haven', 'port'),
  ('zoo', 'dierentuin', 'zoo'),
  ('viaje', 'reis', 'trip'),
  ('coche', 'auto', 'car'),
  ('autobús', 'bus', 'bus'),
  ('tren', 'trein', 'train'),
  ('avión', 'vliegtuig', 'airplane'),
  ('barco', 'boot', 'boat'),
  ('bicicleta', 'fiets', 'bicycle'),
  ('moto', 'motor', 'motorbike'),
  ('taxi', 'taxi', 'taxi'),
  ('metro', 'metro', 'underground'),
  ('camión', 'vrachtwagen', 'truck'),
  ('carretera', 'weg', 'road'),
  ('autopista', 'snelweg', 'motorway'),
  ('semáforo', 'stoplicht', 'traffic light'),
  ('mapa', 'kaart (land)', 'map'),
  ('maleta', 'koffer', 'suitcase'),
  ('mochila', 'rugzak', 'backpack'),
  ('pasaporte', 'paspoort', 'passport'),
  ('billete', 'kaartje', 'ticket'),
  ('entrada', 'ingang', 'entrance'),
  ('salida', 'uitgang', 'exit'),
  ('llegada', 'aankomst', 'arrival'),
  ('destino', 'bestemming', 'destination'),
  ('turista', 'toerist', 'tourist'),
  ('guía', 'gids', 'guide'),
  ('vacaciones', 'vakantie', 'holidays'),
  ('aventura', 'avontuur', 'adventure'),
  ('extranjero', 'buitenland', 'abroad'),
  ('frontera', 'grens', 'border'),
  ('aduana', 'douane', 'customs'),
  ('equipaje', 'bagage', 'luggage'),
  ('asiento', 'zitplaats', 'seat'),
  ('ventanilla', 'loket', 'counter window'),
  ('conductor', 'bestuurder', 'driver'),
  ('pasajero', 'passagier', 'passenger'),
  ('gasolina', 'benzine', 'petrol'),
  ('ropa', 'kleding', 'clothes'),
  ('camisa', 'overhemd', 'shirt'),
  ('camiseta', 't-shirt', 't-shirt'),
  ('pantalón', 'broek', 'trousers'),
  ('falda', 'rok', 'skirt'),
  ('vestido', 'jurk', 'dress'),
  ('abrigo', 'jas', 'coat'),
  ('chaqueta', 'jasje', 'jacket'),
  ('jersey', 'trui', 'sweater'),
  ('traje', 'pak', 'suit'),
  ('corbata', 'stropdas', 'tie'),
  ('calcetín', 'sok', 'sock'),
  ('zapato', 'schoen', 'shoe'),
  ('bota', 'laars', 'boot'),
  ('zapatilla', 'sportschoen', 'trainer'),
  ('sombrero', 'hoed', 'hat'),
  ('gorra', 'pet', 'cap'),
  ('bufanda', 'sjaal', 'scarf'),
  ('guante', 'handschoen', 'glove'),
  ('cinturón', 'riem', 'belt'),
  ('bolsillo', 'zak (kleding)', 'pocket'),
  ('botón', 'knoop', 'button'),
  ('cremallera', 'rits', 'zip'),
  ('gafas', 'bril', 'glasses'),
  ('anillo', 'ring', 'ring'),
  ('collar', 'ketting', 'necklace'),
  ('pendiente', 'oorbel', 'earring'),
  ('paraguas', 'paraplu', 'umbrella'),
  ('pijama', 'pyjama', 'pyjamas'),
  ('bañador', 'zwembroek', 'swimsuit'),
  ('color', 'kleur', 'colour'),
  ('rojo', 'rood', 'red'),
  ('azul', 'blauw', 'blue'),
  ('verde', 'groen', 'green'),
  ('amarillo', 'geel', 'yellow'),
  ('negro', 'zwart', 'black'),
  ('blanco', 'wit', 'white'),
  ('gris', 'grijs', 'grey'),
  ('marrón', 'bruin', 'brown'),
  ('rosa', 'roze', 'pink'),
  ('morado', 'paars', 'purple'),
  ('dorado', 'goudkleurig', 'golden'),
  ('clase', 'les', 'class'),
  ('aula', 'klaslokaal', 'classroom'),
  ('lección', 'les (leerstof)', 'lesson'),
  ('curso', 'cursus', 'course'),
  ('examen', 'examen', 'exam'),
  ('prueba', 'toets', 'test'),
  ('tarea', 'taak', 'task'),
  ('deberes', 'huiswerk', 'homework'),
  ('pregunta', 'vraag', 'question'),
  ('respuesta', 'antwoord', 'answer'),
  ('palabra', 'woord', 'word'),
  ('frase', 'zin', 'sentence'),
  ('texto', 'tekst', 'text'),
  ('página', 'pagina', 'page'),
  ('libro', 'boek', 'book'),
  ('cuaderno', 'schrift', 'notebook'),
  ('lápiz', 'potlood', 'pencil'),
  ('bolígrafo', 'pen', 'pen'),
  ('goma', 'gum', 'eraser'),
  ('regla', 'liniaal', 'ruler'),
  ('tijeras', 'schaar', 'scissors'),
  ('papel', 'papier', 'paper'),
  ('carta', 'brief', 'letter'),
  ('sello', 'postzegel', 'stamp'),
  ('idioma', 'taal', 'language'),
  ('gramática', 'grammatica', 'grammar'),
  ('vocabulario', 'woordenschat', 'vocabulary'),
  ('ejercicio', 'oefening', 'exercise'),
  ('error', 'fout', 'mistake'),
  ('nota', 'cijfer', 'grade'),
  ('diploma', 'diploma', 'diploma'),
  ('estudiante', 'student', 'student'),
  ('alumno', 'leerling', 'pupil'),
  ('profesor', 'docent', 'teacher'),
  ('maestro', 'leraar', 'schoolteacher'),
  ('director', 'directeur', 'director'),
  ('reunión', 'vergadering', 'meeting'),
  ('proyecto', 'project', 'project'),
  ('informe', 'verslag', 'report'),
  ('empresa', 'bedrijf', 'company'),
  ('jefe', 'baas', 'boss'),
  ('empleado', 'werknemer', 'employee'),
  ('sueldo', 'salaris', 'salary'),
  ('trabajo', 'werk', 'work'),
  ('médico', 'dokter', 'doctor'),
  ('enfermero', 'verpleegkundige', 'nurse'),
  ('dentista', 'tandarts', 'dentist'),
  ('abogado', 'advocaat', 'lawyer'),
  ('juez', 'rechter', 'judge'),
  ('policía', 'politieagent', 'police officer'),
  ('bombero', 'brandweerman', 'firefighter'),
  ('soldado', 'soldaat', 'soldier'),
  ('cocinero', 'kok', 'cook'),
  ('camarero', 'ober', 'waiter'),
  ('panadero', 'bakker', 'baker'),
  ('carnicero', 'slager', 'butcher'),
  ('peluquero', 'kapper (persoon)', 'hairdresser'),
  ('mecánico', 'monteur', 'mechanic'),
  ('electricista', 'elektricien', 'electrician'),
  ('carpintero', 'timmerman', 'carpenter'),
  ('pintor', 'schilder', 'painter'),
  ('escritor', 'schrijver', 'writer'),
  ('periodista', 'journalist', 'journalist'),
  ('actor', 'acteur', 'actor'),
  ('cantante', 'zanger', 'singer'),
  ('músico', 'muzikant', 'musician'),
  ('bailarín', 'danser', 'dancer'),
  ('deportista', 'sporter', 'athlete'),
  ('científico', 'wetenschapper', 'scientist'),
  ('ingeniero', 'ingenieur', 'engineer'),
  ('arquitecto', 'architect', 'architect'),
  ('agricultor', 'boer', 'farmer'),
  ('teléfono', 'telefoon', 'telephone'),
  ('móvil', 'mobieltje', 'mobile phone'),
  ('ordenador', 'computer', 'computer'),
  ('pantalla', 'scherm', 'screen'),
  ('teclado', 'toetsenbord', 'keyboard'),
  ('internet', 'internet', 'internet'),
  ('red', 'netwerk', 'network'),
  ('mensaje', 'bericht', 'message'),
  ('foto', 'foto', 'photo'),
  ('cámara', 'camera', 'camera'),
  ('vídeo', 'video', 'video'),
  ('radio', 'radio', 'radio'),
  ('televisión', 'televisie', 'television'),
  ('película', 'film', 'film'),
  ('canal', 'kanaal', 'channel'),
  ('noticia', 'nieuwsbericht', 'news item'),
  ('aplicación', 'app', 'application'),
  ('juego', 'spel', 'game'),
  ('batería', 'batterij', 'battery'),
  ('cargador', 'oplader', 'charger'),
  ('auricular', 'koptelefoon', 'headphone'),
  ('impresora', 'printer', 'printer'),
  ('salud', 'gezondheid', 'health'),
  ('enfermedad', 'ziekte', 'illness'),
  ('fiebre', 'koorts', 'fever'),
  ('gripe', 'griep', 'flu'),
  ('tos', 'hoest', 'cough'),
  ('dolor', 'pijn', 'pain'),
  ('herida', 'wond', 'wound'),
  ('medicina', 'medicijn', 'medicine'),
  ('pastilla', 'pil', 'pill'),
  ('cita', 'afspraak', 'appointment'),
  ('consulta', 'spreekuur', 'consultation'),
  ('urgencias', 'spoedeisende hulp', 'emergency room'),
  ('ambulancia', 'ambulance', 'ambulance'),
  ('seguro', 'verzekering', 'insurance'),
  ('dieta', 'dieet', 'diet'),
  ('descanso', 'rust', 'rest'),
  ('sueño', 'slaap', 'sleep'),
  ('energía', 'energie', 'energy'),
  ('fuerza', 'kracht', 'strength'),
  ('peso', 'gewicht', 'weight'),
  ('altura', 'lengte (hoogte)', 'height'),
  ('edad', 'leeftijd', 'age'),
  ('vida', 'leven', 'life'),
  ('muerte', 'dood', 'death'),
  ('deporte', 'sport', 'sport'),
  ('fútbol', 'voetbal', 'football'),
  ('baloncesto', 'basketbal', 'basketball'),
  ('tenis', 'tennis', 'tennis'),
  ('natación', 'zwemsport', 'swimming'),
  ('ciclismo', 'wielrennen', 'cycling'),
  ('atletismo', 'atletiek', 'athletics'),
  ('equipo', 'team', 'team'),
  ('partido', 'wedstrijd', 'match'),
  ('pelota', 'bal (klein)', 'ball'),
  ('balón', 'bal (groot)', 'ball'),
  ('gol', 'doelpunt', 'goal'),
  ('premio', 'prijs (beloning)', 'prize'),
  ('campeón', 'kampioen', 'champion'),
  ('carrera', 'race', 'race'),
  ('meta', 'finish', 'finish line'),
  ('afición', 'hobby', 'hobby'),
  ('pasatiempo', 'tijdverdrijf', 'pastime'),
  ('ajedrez', 'schaken', 'chess'),
  ('pesca', 'vissen (sport)', 'fishing'),
  ('caza', 'jacht', 'hunting'),
  ('senderismo', 'wandelsport', 'hiking'),
  ('camping', 'camping', 'camping'),
  ('esquí', 'skiën', 'skiing'),
  ('patinaje', 'schaatsen', 'skating'),
  ('yoga', 'yoga', 'yoga'),
  ('música', 'muziek', 'music'),
  ('canción', 'lied', 'song'),
  ('ritmo', 'ritme', 'rhythm'),
  ('melodía', 'melodie', 'melody'),
  ('concierto', 'concert', 'concert'),
  ('guitarra', 'gitaar', 'guitar'),
  ('piano', 'piano', 'piano'),
  ('violín', 'viool', 'violin'),
  ('tambor', 'trommel', 'drum'),
  ('flauta', 'fluit', 'flute'),
  ('orquesta', 'orkest', 'orchestra'),
  ('arte', 'kunst', 'art'),
  ('pintura', 'schilderkunst', 'painting (art)'),
  ('dibujo', 'tekening', 'drawing'),
  ('escultura', 'beeldhouwwerk', 'sculpture'),
  ('poesía', 'poëzie', 'poetry'),
  ('poema', 'gedicht', 'poem'),
  ('novela', 'roman', 'novel'),
  ('cuento', 'verhaal', 'story'),
  ('escenario', 'podium', 'stage'),
  ('dinero', 'geld', 'money'),
  ('precio', 'prijs (kosten)', 'price'),
  ('oferta', 'aanbieding', 'offer'),
  ('descuento', 'korting', 'discount'),
  ('rebajas', 'uitverkoop', 'sales'),
  ('caja', 'kassa', 'checkout'),
  ('tarjeta', 'kaart (pas)', 'card'),
  ('moneda', 'munt', 'coin'),
  ('cambio', 'wisselgeld', 'change'),
  ('cuenta', 'rekening', 'bill'),
  ('factura', 'factuur', 'invoice'),
  ('recibo', 'bonnetje', 'receipt'),
  ('regalo', 'cadeau', 'present'),
  ('compra', 'aankoop', 'purchase'),
  ('venta', 'verkoop', 'sale'),
  ('cliente', 'klant', 'customer'),
  ('cesta', 'mandje', 'basket'),
  ('carrito', 'winkelwagen', 'trolley'),
  ('marca', 'merk', 'brand'),
  ('talla', 'maat', 'size'),
  ('calidad', 'kwaliteit', 'quality'),
  ('euro', 'euro', 'euro'),
  ('amor', 'liefde', 'love'),
  ('odio', 'haat', 'hate'),
  ('miedo', 'angst', 'fear'),
  ('alegría', 'vreugde', 'joy'),
  ('tristeza', 'verdriet', 'sadness'),
  ('sorpresa', 'verrassing', 'surprise'),
  ('esperanza', 'hoop', 'hope'),
  ('deseo', 'wens', 'wish'),
  ('beso', 'kus', 'kiss'),
  ('abrazo', 'knuffel', 'hug'),
  ('sonrisa', 'glimlach', 'smile'),
  ('risa', 'lach', 'laughter'),
  ('lágrima', 'traan', 'tear'),
  ('problema', 'probleem', 'problem'),
  ('solución', 'oplossing', 'solution'),
  ('idea', 'idee', 'idea'),
  ('pensamiento', 'gedachte', 'thought'),
  ('memoria', 'geheugen', 'memory'),
  ('recuerdo', 'herinnering', 'memory (recollection)'),
  ('verdad', 'waarheid', 'truth'),
  ('mentira', 'leugen', 'lie'),
  ('secreto', 'geheim', 'secret'),
  ('historia', 'geschiedenis', 'history'),
  ('suerte', 'geluk (mazzel)', 'luck'),
  ('paz', 'vrede', 'peace'),
  ('guerra', 'oorlog', 'war'),
  ('libertad', 'vrijheid', 'freedom'),
  ('justicia', 'rechtvaardigheid', 'justice'),
  ('ley', 'wet', 'law'),
  ('cultura', 'cultuur', 'culture'),
  ('grande', 'groot', 'big'),
  ('pequeño', 'klein', 'small'),
  ('alto', 'lang (persoon)', 'tall'),
  ('bajo', 'kort (persoon)', 'short (height)'),
  ('largo', 'lang', 'long'),
  ('corto', 'kort', 'short'),
  ('ancho', 'breed', 'wide'),
  ('estrecho', 'smal', 'narrow'),
  ('gordo', 'dik', 'fat'),
  ('delgado', 'dun', 'thin'),
  ('fuerte', 'sterk', 'strong'),
  ('débil', 'zwak', 'weak'),
  ('rápido', 'snel', 'fast'),
  ('lento', 'langzaam', 'slow'),
  ('nuevo', 'nieuw', 'new'),
  ('viejo', 'oud', 'old'),
  ('bueno', 'goed', 'good'),
  ('malo', 'slecht', 'bad'),
  ('mejor', 'beter', 'better'),
  ('peor', 'slechter', 'worse'),
  ('bonito', 'mooi', 'pretty'),
  ('feo', 'lelijk', 'ugly'),
  ('hermoso', 'prachtig', 'beautiful'),
  ('guapo', 'knap', 'handsome'),
  ('limpio', 'schoon', 'clean'),
  ('sucio', 'vies', 'dirty'),
  ('lleno', 'vol', 'full'),
  ('vacío', 'leeg', 'empty'),
  ('abierto', 'open', 'open'),
  ('cerrado', 'gesloten', 'closed'),
  ('caliente', 'heet', 'hot'),
  ('frío', 'koud', 'cold'),
  ('caro', 'duur', 'expensive'),
  ('barato', 'goedkoop', 'cheap'),
  ('rico', 'rijk', 'rich'),
  ('pobre', 'arm', 'poor'),
  ('fácil', 'makkelijk', 'easy'),
  ('difícil', 'moeilijk', 'difficult'),
  ('feliz', 'gelukkig', 'happy'),
  ('triste', 'verdrietig', 'sad'),
  ('contento', 'blij', 'glad'),
  ('enfadado', 'boos', 'angry'),
  ('cansado', 'moe', 'tired'),
  ('enfermo', 'ziek', 'ill'),
  ('sano', 'gezond', 'healthy'),
  ('vivo', 'levend', 'alive'),
  ('muerto', 'dood (bn.)', 'dead'),
  ('ocupado', 'bezet', 'busy'),
  ('libre', 'vrij', 'free'),
  ('tranquilo', 'rustig', 'calm'),
  ('nervioso', 'zenuwachtig', 'nervous'),
  ('valiente', 'dapper', 'brave'),
  ('tímido', 'verlegen', 'shy'),
  ('simpático', 'aardig', 'nice'),
  ('antipático', 'onaardig', 'unfriendly'),
  ('amable', 'vriendelijk', 'kind'),
  ('serio', 'serieus', 'serious'),
  ('divertido', 'leuk', 'fun'),
  ('aburrido', 'saai', 'boring'),
  ('interesante', 'interessant', 'interesting'),
  ('importante', 'belangrijk', 'important'),
  ('necesario', 'nodig', 'necessary'),
  ('posible', 'mogelijk', 'possible'),
  ('imposible', 'onmogelijk', 'impossible'),
  ('correcto', 'juist', 'correct'),
  ('falso', 'onjuist', 'false'),
  ('verdadero', 'waar', 'true'),
  ('igual', 'gelijk', 'equal'),
  ('diferente', 'verschillend', 'different'),
  ('similar', 'vergelijkbaar', 'similar'),
  ('extraño', 'vreemd', 'strange'),
  ('normal', 'normaal', 'normal'),
  ('especial', 'bijzonder', 'special'),
  ('famoso', 'beroemd', 'famous'),
  ('conocido', 'bekend', 'well-known'),
  ('peligroso', 'gevaarlijk', 'dangerous'),
  ('dulce', 'zoet', 'sweet'),
  ('amargo', 'bitter', 'bitter'),
  ('salado', 'zout (bn.)', 'salty'),
  ('picante', 'pittig', 'spicy'),
  ('suave', 'zacht', 'soft'),
  ('duro', 'hard', 'hard'),
  ('blando', 'week (zacht)', 'tender'),
  ('pesado', 'zwaar', 'heavy'),
  ('ligero', 'licht (gewicht)', 'light'),
  ('oscuro', 'donker', 'dark'),
  ('claro', 'helder', 'clear'),
  ('brillante', 'stralend', 'bright'),
  ('mojado', 'nat', 'wet'),
  ('seco', 'droog', 'dry'),
  ('listo', 'slim', 'clever'),
  ('tonto', 'dom', 'silly'),
  ('loco', 'gek', 'crazy'),
  ('sabio', 'wijs', 'wise'),
  ('ser', 'zijn', 'to be'),
  ('estar', 'zijn (toestand)', 'to be (state)'),
  ('tener', 'hebben', 'to have'),
  ('hacer', 'doen', 'to do'),
  ('poder', 'kunnen', 'to be able'),
  ('decir', 'zeggen', 'to say'),
  ('ir', 'gaan', 'to go'),
  ('ver', 'zien', 'to see'),
  ('dar', 'geven', 'to give'),
  ('saber', 'weten', 'to know'),
  ('querer', 'willen', 'to want'),
  ('llegar', 'aankomen', 'to arrive'),
  ('pasar', 'passeren', 'to pass'),
  ('deber', 'moeten', 'must'),
  ('poner', 'zetten', 'to put'),
  ('parecer', 'lijken', 'to seem'),
  ('quedar', 'overblijven', 'to remain'),
  ('creer', 'geloven', 'to believe'),
  ('hablar', 'spreken', 'to speak'),
  ('llevar', 'dragen', 'to carry'),
  ('dejar', 'laten', 'to let'),
  ('seguir', 'volgen', 'to follow'),
  ('encontrar', 'vinden', 'to find'),
  ('llamar', 'bellen', 'to call'),
  ('venir', 'komen', 'to come'),
  ('pensar', 'denken', 'to think'),
  ('salir', 'uitgaan', 'to go out'),
  ('volver', 'terugkeren', 'to return'),
  ('tomar', 'nemen', 'to take'),
  ('conocer', 'kennen', 'to know (someone)'),
  ('vivir', 'wonen', 'to live'),
  ('sentir', 'voelen', 'to feel'),
  ('mirar', 'kijken', 'to look'),
  ('contar', 'tellen', 'to count'),
  ('empezar', 'beginnen', 'to begin'),
  ('esperar', 'wachten', 'to wait'),
  ('buscar', 'zoeken', 'to search'),
  ('entrar', 'binnenkomen', 'to enter'),
  ('trabajar', 'werken', 'to work'),
  ('escribir', 'schrijven', 'to write'),
  ('perder', 'verliezen', 'to lose'),
  ('entender', 'begrijpen', 'to understand'),
  ('pedir', 'vragen om', 'to ask for'),
  ('recibir', 'ontvangen', 'to receive'),
  ('recordar', 'zich herinneren', 'to remember'),
  ('terminar', 'eindigen', 'to finish'),
  ('permitir', 'toestaan', 'to allow'),
  ('aparecer', 'verschijnen', 'to appear'),
  ('conseguir', 'krijgen', 'to obtain'),
  ('comenzar', 'aanvangen', 'to commence'),
  ('servir', 'serveren', 'to serve'),
  ('sacar', 'eruit halen', 'to take out'),
  ('necesitar', 'nodig hebben', 'to need'),
  ('mantener', 'onderhouden', 'to maintain'),
  ('leer', 'lezen', 'to read'),
  ('caer', 'vallen', 'to fall'),
  ('cambiar', 'veranderen', 'to change'),
  ('crear', 'creëren', 'to create'),
  ('abrir', 'openen', 'to open'),
  ('oír', 'horen', 'to hear'),
  ('acabar', 'afmaken', 'to end'),
  ('ganar', 'winnen', 'to win'),
  ('formar', 'vormen', 'to form'),
  ('traer', 'meebrengen', 'to bring'),
  ('morir', 'sterven', 'to die'),
  ('aceptar', 'accepteren', 'to accept'),
  ('suponer', 'veronderstellen', 'to suppose'),
  ('comprender', 'snappen', 'to comprehend'),
  ('lograr', 'bereiken', 'to achieve'),
  ('explicar', 'uitleggen', 'to explain'),
  ('preguntar', 'vragen', 'to ask'),
  ('tocar', 'aanraken', 'to touch'),
  ('reconocer', 'herkennen', 'to recognise'),
  ('estudiar', 'studeren', 'to study'),
  ('nacer', 'geboren worden', 'to be born'),
  ('correr', 'rennen', 'to run'),
  ('utilizar', 'toepassen', 'to utilise'),
  ('pagar', 'betalen', 'to pay'),
  ('ayudar', 'helpen', 'to help'),
  ('gustar', 'leuk vinden', 'to like'),
  ('jugar', 'spelen', 'to play'),
  ('escuchar', 'luisteren', 'to listen'),
  ('ofrecer', 'aanbieden', 'to offer'),
  ('descubrir', 'ontdekken', 'to discover'),
  ('levantar', 'optillen', 'to lift'),
  ('intentar', 'proberen', 'to try'),
  ('usar', 'gebruiken', 'to use'),
  ('decidir', 'beslissen', 'to decide'),
  ('repetir', 'herhalen', 'to repeat'),
  ('olvidar', 'vergeten', 'to forget'),
  ('comer', 'eten (ww.)', 'to eat'),
  ('mostrar', 'tonen', 'to show'),
  ('mover', 'bewegen', 'to move'),
  ('continuar', 'doorgaan', 'to continue'),
  ('aprender', 'leren', 'to learn'),
  ('comprar', 'kopen', 'to buy'),
  ('subir', 'omhooggaan', 'to go up'),
  ('bajar', 'naar beneden gaan', 'to go down'),
  ('evitar', 'vermijden', 'to avoid'),
  ('cerrar', 'sluiten', 'to close'),
  ('responder', 'antwoorden', 'to answer'),
  ('sufrir', 'lijden', 'to suffer'),
  ('obtener', 'verkrijgen', 'to get'),
  ('observar', 'observeren', 'to observe'),
  ('imaginar', 'zich voorstellen', 'to imagine'),
  ('elegir', 'kiezen', 'to choose'),
  ('preparar', 'voorbereiden', 'to prepare'),
  ('proponer', 'voorstellen', 'to propose'),
  ('demostrar', 'aantonen', 'to demonstrate'),
  ('significar', 'betekenen', 'to mean'),
  ('reunir', 'verzamelen', 'to gather'),
  ('faltar', 'ontbreken', 'to lack'),
  ('acompañar', 'vergezellen', 'to accompany'),
  ('desear', 'wensen', 'to desire'),
  ('enseñar', 'onderwijzen', 'to teach'),
  ('construir', 'bouwen', 'to build'),
  ('vender', 'verkopen', 'to sell'),
  ('defender', 'verdedigen', 'to defend'),
  ('invitar', 'uitnodigen', 'to invite'),
  ('cantar', 'zingen', 'to sing'),
  ('bailar', 'dansen', 'to dance'),
  ('dormir', 'slapen', 'to sleep'),
  ('viajar', 'reizen', 'to travel'),
  ('nadar', 'zwemmen', 'to swim'),
  ('cocinar', 'koken', 'to cook'),
  ('limpiar', 'schoonmaken', 'to clean'),
  ('lavar', 'wassen', 'to wash'),
  ('romper', 'breken', 'to break'),
  ('reír', 'lachen', 'to laugh'),
  ('llorar', 'huilen', 'to cry'),
  ('besar', 'kussen (ww.)', 'to kiss'),
  ('abrazar', 'knuffelen', 'to hug'),
  ('saludar', 'begroeten', 'to greet'),
  ('caminar', 'wandelen', 'to walk'),
  ('andar', 'lopen', 'to stroll'),
  ('volar', 'vliegen', 'to fly'),
  ('conducir', 'autorijden', 'to drive'),
  ('montar', 'rijden op', 'to ride'),
  ('descansar', 'uitrusten', 'to rest'),
  ('despertar', 'wakker worden', 'to wake up'),
  ('celebrar', 'vieren', 'to celebrate'),
  ('felicitar', 'feliciteren', 'to congratulate'),
  ('regalar', 'cadeau geven', 'to gift'),
  ('apagar', 'uitzetten', 'to turn off'),
  ('encender', 'aanzetten', 'to turn on'),
  ('llenar', 'vullen', 'to fill'),
  ('guardar', 'bewaren', 'to keep'),
  ('enviar', 'versturen', 'to send'),
  ('beber', 'drinken', 'to drink'),
  ('soñar', 'dromen', 'to dream'),
  ('sí', 'ja', 'yes'),
  ('no', 'nee', 'no'),
  ('quizás', 'misschien', 'maybe'),
  ('también', 'ook', 'also'),
  ('tampoco', 'ook niet', 'neither'),
  ('siempre', 'altijd', 'always'),
  ('nunca', 'nooit', 'never'),
  ('luego', 'daarna', 'later'),
  ('después', 'na', 'after'),
  ('antes', 'voor (eerder)', 'before'),
  ('durante', 'tijdens', 'during'),
  ('mientras', 'terwijl', 'while'),
  ('ya', 'al', 'already'),
  ('todavía', 'nog', 'still'),
  ('aquí', 'hier', 'here'),
  ('allí', 'daar', 'there'),
  ('cerca', 'dichtbij', 'near'),
  ('lejos', 'ver weg', 'far'),
  ('arriba', 'boven', 'up'),
  ('abajo', 'beneden', 'down'),
  ('dentro', 'binnen', 'inside'),
  ('fuera', 'buiten', 'outside'),
  ('delante', 'vooraan', 'in front'),
  ('detrás', 'achter', 'behind'),
  ('encima', 'bovenop', 'on top'),
  ('debajo', 'onder', 'underneath'),
  ('entre', 'tussen', 'between'),
  ('junto', 'naast', 'next to'),
  ('alrededor', 'rondom', 'around'),
  ('muy', 'heel', 'very'),
  ('mucho', 'veel', 'much'),
  ('poco', 'weinig', 'little'),
  ('bastante', 'best wel', 'quite'),
  ('demasiado', 'te veel', 'too much'),
  ('casi', 'bijna', 'almost'),
  ('solo', 'alleen', 'only'),
  ('bien', 'goed (bw.)', 'well'),
  ('mal', 'slecht (bw.)', 'badly'),
  ('despacio', 'langzaam (bw.)', 'slowly'),
  ('además', 'bovendien', 'moreover'),
  ('entonces', 'toen', 'then'),
  ('pero', 'maar', 'but'),
  ('porque', 'omdat', 'because'),
  ('aunque', 'hoewel', 'although'),
  ('cuando', 'wanneer', 'when'),
  ('donde', 'waar', 'where'),
  ('como', 'zoals', 'like (as)'),
  ('qué', 'wat', 'what'),
  ('quién', 'wie', 'who'),
  ('cuál', 'welke', 'which'),
  ('cuánto', 'hoeveel', 'how much'),
  ('nada', 'niets', 'nothing'),
  ('algo', 'iets', 'something'),
  ('todo', 'alles', 'everything'),
  ('nadie', 'niemand', 'nobody'),
  ('alguien', 'iemand', 'somebody'),
  ('cada', 'elke', 'each'),
  ('otro', 'ander', 'other'),
  ('mismo', 'zelfde', 'same'),
  ('este', 'deze', 'this'),
  ('ese', 'die', 'that'),
  ('aquel', 'gindse', 'that (over there)'),
  ('con', 'met', 'with'),
  ('sin', 'zonder', 'without'),
  ('para', 'voor (bestemd)', 'for'),
  ('por', 'door', 'by'),
  ('sobre', 'over', 'about'),
  ('hasta', 'tot', 'until'),
  ('desde', 'vanaf', 'from'),
  ('hacia', 'naar', 'towards'),
  ('contra', 'tegen', 'against'),
  ('según', 'volgens', 'according to'),
  ('gracias', 'dank je', 'thank you'),
  ('hola', 'hallo', 'hello'),
  ('adiós', 'tot ziens', 'goodbye'),
  ('perdón', 'sorry', 'sorry'),
  ('bienvenido', 'welkom', 'welcome'),
  ('yerno', 'schoonzoon', 'son-in-law'),
  ('nuera', 'schoondochter', 'daughter-in-law'),
  ('suegro', 'schoonvader', 'father-in-law'),
  ('suegra', 'schoonmoeder', 'mother-in-law'),
  ('cuñado', 'zwager', 'brother-in-law'),
  ('cuñada', 'schoonzus', 'sister-in-law'),
  ('padrino', 'peetvader', 'godfather'),
  ('madrina', 'peetmoeder', 'godmother'),
  ('gemelo', 'tweelingbroer', 'twin'),
  ('viudo', 'weduwnaar', 'widower'),
  ('viuda', 'weduwe', 'widow'),
  ('huérfano', 'wees', 'orphan'),
  ('antepasado', 'voorouder', 'ancestor'),
  ('pariente', 'familielid', 'relative'),
  ('nieta', 'kleindochter', 'granddaughter'),
  ('bisabuelo', 'overgrootvader', 'great-grandfather'),
  ('frente', 'voorhoofd', 'forehead'),
  ('mejilla', 'wang', 'cheek'),
  ('barbilla', 'kin', 'chin'),
  ('ceja', 'wenkbrauw', 'eyebrow'),
  ('pestaña', 'wimper', 'eyelash'),
  ('párpado', 'ooglid', 'eyelid'),
  ('muñeca', 'pols', 'wrist'),
  ('tobillo', 'enkel', 'ankle'),
  ('talón', 'hiel', 'heel'),
  ('puño', 'vuist', 'fist'),
  ('cadera', 'heup', 'hip'),
  ('cintura', 'taille', 'waist'),
  ('pulmón', 'long', 'lung'),
  ('hígado', 'lever', 'liver'),
  ('riñón', 'nier', 'kidney'),
  ('garganta', 'keel', 'throat'),
  ('vena', 'ader', 'vein'),
  ('nervio', 'zenuw', 'nerve'),
  ('costilla', 'rib', 'rib'),
  ('cráneo', 'schedel', 'skull'),
  ('toro', 'stier', 'bull'),
  ('ternero', 'kalf', 'calf'),
  ('yegua', 'merrie', 'mare'),
  ('cordero', 'lam', 'lamb'),
  ('mula', 'muildier', 'mule'),
  ('camello', 'kameel', 'camel'),
  ('jirafa', 'giraf', 'giraffe'),
  ('cebra', 'zebra', 'zebra'),
  ('rinoceronte', 'neushoorn', 'rhinoceros'),
  ('hipopótamo', 'nijlpaard', 'hippopotamus'),
  ('cocodrilo', 'krokodil', 'crocodile'),
  ('lagarto', 'hagedis', 'lizard'),
  ('gusano', 'worm', 'worm'),
  ('caracol', 'slak', 'snail'),
  ('mosquito', 'mug', 'mosquito'),
  ('escarabajo', 'kever', 'beetle'),
  ('cangrejo', 'krab', 'crab'),
  ('pulpo', 'octopus', 'octopus'),
  ('foca', 'zeehond', 'seal'),
  ('pingüino', 'pinguïn', 'penguin'),
  ('loro', 'papegaai', 'parrot'),
  ('búho', 'uil', 'owl'),
  ('cuervo', 'kraai', 'crow'),
  ('paloma', 'duif', 'pigeon'),
  ('gaviota', 'meeuw', 'seagull'),
  ('cisne', 'zwaan', 'swan'),
  ('pavo', 'kalkoen', 'turkey'),
  ('ardilla', 'eekhoorn', 'squirrel'),
  ('murciélago', 'vleermuis', 'bat'),
  ('ganso', 'gans', 'goose'),
  ('harina', 'meel', 'flour'),
  ('masa', 'deeg', 'dough'),
  ('trigo', 'tarwe', 'wheat'),
  ('maíz', 'maïs', 'corn'),
  ('avena', 'haver', 'oats'),
  ('guisante', 'erwt', 'pea'),
  ('lenteja', 'linze', 'lentil'),
  ('garbanzo', 'kikkererwt', 'chickpea'),
  ('espinaca', 'spinazie', 'spinach'),
  ('col', 'kool', 'cabbage'),
  ('pepino', 'komkommer', 'cucumber'),
  ('pimiento', 'paprika', 'pepper'),
  ('calabaza', 'pompoen', 'pumpkin'),
  ('champiñón', 'champignon', 'mushroom'),
  ('aceituna', 'olijf', 'olive'),
  ('nuez', 'walnoot', 'walnut'),
  ('almendra', 'amandel', 'almond'),
  ('cacahuete', 'pinda', 'peanut'),
  ('piña', 'ananas', 'pineapple'),
  ('mango', 'mango', 'mango'),
  ('coco', 'kokosnoot', 'coconut'),
  ('cereza', 'kers', 'cherry'),
  ('ciruela', 'pruim', 'plum'),
  ('melocotón', 'perzik', 'peach'),
  ('frambuesa', 'framboos', 'raspberry'),
  ('mandarina', 'mandarijn', 'tangerine'),
  ('ternera', 'rundvlees', 'beef'),
  ('chuleta', 'karbonade', 'chop'),
  ('filete', 'biefstuk', 'steak'),
  ('gamba', 'garnaal', 'prawn'),
  ('atún', 'tonijn', 'tuna'),
  ('tortilla', 'omelet', 'omelette'),
  ('bocadillo', 'broodje', 'sandwich'),
  ('caramelo', 'snoepje', 'sweet'),
  ('mermelada', 'jam', 'jam'),
  ('nata', 'slagroom', 'cream'),
  ('batido', 'milkshake', 'milkshake'),
  ('limonada', 'limonade', 'lemonade'),
  ('sidra', 'cider', 'cider'),
  ('licor', 'likeur', 'liqueur'),
  ('sartén', 'koekenpan', 'frying pan'),
  ('olla', 'pan', 'pot'),
  ('bandeja', 'dienblad', 'tray'),
  ('cafetera', 'koffiezetapparaat', 'coffee maker'),
  ('microondas', 'magnetron', 'microwave'),
  ('lavadora', 'wasmachine', 'washing machine'),
  ('lavavajillas', 'vaatwasser', 'dishwasher'),
  ('plancha', 'strijkijzer', 'iron'),
  ('aspiradora', 'stofzuiger', 'vacuum cleaner'),
  ('escoba', 'bezem', 'broom'),
  ('cubo', 'emmer', 'bucket'),
  ('esponja', 'spons', 'sponge'),
  ('detergente', 'wasmiddel', 'detergent'),
  ('fregadero', 'gootsteen', 'sink'),
  ('grifo', 'kraan', 'tap'),
  ('enchufe', 'stopcontact', 'socket'),
  ('bombilla', 'gloeilamp', 'light bulb'),
  ('vela', 'kaars', 'candle'),
  ('delantal', 'schort', 'apron'),
  ('herramienta', 'gereedschap', 'tool'),
  ('martillo', 'hamer', 'hammer'),
  ('clavo', 'spijker', 'nail'),
  ('tornillo', 'schroef', 'screw'),
  ('destornillador', 'schroevendraaier', 'screwdriver'),
  ('taladro', 'boormachine', 'drill'),
  ('sierra', 'zaag', 'saw'),
  ('pincel', 'penseel', 'paintbrush'),
  ('pegamento', 'lijm', 'glue'),
  ('cuerda', 'touw', 'rope'),
  ('cadena', 'ketting', 'chain'),
  ('madera', 'hout', 'wood'),
  ('hierro', 'ijzer', 'iron'),
  ('acero', 'staal', 'steel'),
  ('oro', 'goud', 'gold'),
  ('plata', 'zilver', 'silver'),
  ('cobre', 'koper', 'copper'),
  ('plástico', 'plastic', 'plastic'),
  ('vidrio', 'glas', 'glass'),
  ('cartón', 'karton', 'cardboard'),
  ('tela', 'stof', 'fabric'),
  ('algodón', 'katoen', 'cotton'),
  ('lana', 'wol', 'wool'),
  ('seda', 'zijde', 'silk'),
  ('cuero', 'leer', 'leather'),
  ('ladrillo', 'baksteen', 'brick'),
  ('cemento', 'cement', 'cement'),
  ('mármol', 'marmer', 'marble'),
  ('arcilla', 'klei', 'clay'),
  ('carbón', 'steenkool', 'coal'),
  ('amanecer', 'zonsopgang', 'sunrise'),
  ('atardecer', 'zonsondergang', 'sunset'),
  ('horizonte', 'horizon', 'horizon'),
  ('sombra', 'schaduw', 'shadow'),
  ('terremoto', 'aardbeving', 'earthquake'),
  ('inundación', 'overstroming', 'flood'),
  ('sequía', 'droogte', 'drought'),
  ('volcán', 'vulkaan', 'volcano'),
  ('cueva', 'grot', 'cave'),
  ('acantilado', 'klif', 'cliff'),
  ('costa', 'kust', 'coast'),
  ('bahía', 'baai', 'bay'),
  ('península', 'schiereiland', 'peninsula'),
  ('continente', 'continent', 'continent'),
  ('marea', 'getij', 'tide'),
  ('cascada', 'waterval', 'waterfall'),
  ('llanura', 'vlakte', 'plain'),
  ('sendero', 'pad', 'path'),
  ('relámpago', 'bliksem', 'lightning'),
  ('granizo', 'hagel', 'hail'),
  ('rocío', 'dauw', 'dew'),
  ('mundo', 'wereld', 'world'),
  ('tronco', 'stam', 'trunk'),
  ('corteza', 'bast', 'bark'),
  ('espina', 'doorn', 'thorn'),
  ('musgo', 'mos', 'moss'),
  ('arbusto', 'struik', 'bush'),
  ('cactus', 'cactus', 'cactus'),
  ('palmera', 'palmboom', 'palm tree'),
  ('pino', 'den', 'pine'),
  ('roble', 'eik', 'oak'),
  ('cosecha', 'oogst', 'harvest'),
  ('tallo', 'steel', 'stem'),
  ('brote', 'scheut', 'sprout'),
  ('planeta', 'planeet', 'planet'),
  ('galaxia', 'melkweg', 'galaxy'),
  ('universo', 'heelal', 'universe'),
  ('cometa', 'komeet', 'comet'),
  ('satélite', 'satelliet', 'satellite'),
  ('órbita', 'baan', 'orbit'),
  ('eclipse', 'eclips', 'eclipse'),
  ('espacio', 'ruimte', 'space'),
  ('gravedad', 'zwaartekracht', 'gravity'),
  ('país', 'land', 'country'),
  ('nación', 'natie', 'nation'),
  ('capital', 'hoofdstad', 'capital'),
  ('bandera', 'vlag', 'flag'),
  ('ciudadano', 'burger', 'citizen'),
  ('España', 'Spanje', 'Spain'),
  ('Francia', 'Frankrijk', 'France'),
  ('Alemania', 'Duitsland', 'Germany'),
  ('Italia', 'Italië', 'Italy'),
  ('Inglaterra', 'Engeland', 'England'),
  ('Europa', 'Europa', 'Europe'),
  ('español', 'Spaans', 'Spanish'),
  ('francés', 'Frans', 'French'),
  ('alemán', 'Duits', 'German'),
  ('inglés', 'Engels', 'English'),
  ('norte', 'noorden', 'north'),
  ('sur', 'zuiden', 'south'),
  ('oriente', 'oosten', 'east'),
  ('oeste', 'westen', 'west'),
  ('izquierda', 'links', 'left'),
  ('derecha', 'rechts', 'right'),
  ('centro', 'centrum', 'centre'),
  ('lado', 'kant', 'side'),
  ('borde', 'rand', 'edge'),
  ('orgullo', 'trots', 'pride'),
  ('vergüenza', 'schaamte', 'shame'),
  ('envidia', 'jaloezie', 'envy'),
  ('culpa', 'schuld', 'guilt'),
  ('ansiedad', 'angst', 'anxiety'),
  ('estrés', 'stress', 'stress'),
  ('calma', 'kalmte', 'calm'),
  ('pánico', 'paniek', 'panic'),
  ('rabia', 'woede', 'rage'),
  ('cariño', 'genegenheid', 'affection'),
  ('gratitud', 'dankbaarheid', 'gratitude'),
  ('respeto', 'respect', 'respect'),
  ('confianza', 'vertrouwen', 'trust'),
  ('duda', 'twijfel', 'doubt'),
  ('curiosidad', 'nieuwsgierigheid', 'curiosity'),
  ('entusiasmo', 'enthousiasme', 'enthusiasm'),
  ('decepción', 'teleurstelling', 'disappointment'),
  ('soledad', 'eenzaamheid', 'loneliness'),
  ('paciencia', 'geduld', 'patience'),
  ('valor', 'moed', 'courage'),
  ('sociedad', 'maatschappij', 'society'),
  ('gobierno', 'regering', 'government'),
  ('democracia', 'democratie', 'democracy'),
  ('elección', 'verkiezing', 'election'),
  ('voto', 'stem', 'vote'),
  ('delito', 'misdrijf', 'crime'),
  ('ladrón', 'dief', 'thief'),
  ('robo', 'diefstal', 'theft'),
  ('cárcel', 'gevangenis', 'prison'),
  ('juicio', 'proces', 'trial'),
  ('testigo', 'getuige', 'witness'),
  ('víctima', 'slachtoffer', 'victim'),
  ('culpable', 'schuldig', 'guilty'),
  ('inocente', 'onschuldig', 'innocent'),
  ('castigo', 'straf', 'punishment'),
  ('permiso', 'toestemming', 'permission'),
  ('norma', 'norm', 'norm'),
  ('dios', 'god', 'god'),
  ('templo', 'tempel', 'temple'),
  ('alma', 'ziel', 'soul'),
  ('espíritu', 'geest', 'spirit'),
  ('fe', 'geloof', 'faith'),
  ('oración', 'gebed', 'prayer'),
  ('santo', 'heilige', 'saint'),
  ('ángel', 'engel', 'angel'),
  ('milagro', 'wonder', 'miracle'),
  ('pecado', 'zonde', 'sin'),
  ('infierno', 'hel', 'hell'),
  ('economía', 'economie', 'economy'),
  ('negocio', 'zaak', 'business'),
  ('bolsa', 'beurs', 'stock exchange'),
  ('inversión', 'investering', 'investment'),
  ('deuda', 'schuld', 'debt'),
  ('préstamo', 'lening', 'loan'),
  ('impuesto', 'belasting', 'tax'),
  ('presupuesto', 'begroting', 'budget'),
  ('ganancia', 'winst', 'profit'),
  ('pérdida', 'verlies', 'loss'),
  ('riqueza', 'rijkdom', 'wealth'),
  ('pobreza', 'armoede', 'poverty'),
  ('herencia', 'erfenis', 'inheritance'),
  ('contrato', 'contract', 'contract'),
  ('empleo', 'baan', 'job'),
  ('huelga', 'staking', 'strike'),
  ('socio', 'partner', 'partner'),
  ('proveedor', 'leverancier', 'supplier'),
  ('publicidad', 'reclame', 'advertising'),
  ('conversación', 'gesprek', 'conversation'),
  ('discusión', 'discussie', 'discussion'),
  ('entrevista', 'interview', 'interview'),
  ('discurso', 'toespraak', 'speech'),
  ('llamada', 'telefoontje', 'call'),
  ('grito', 'schreeuw', 'shout'),
  ('silencio', 'stilte', 'silence'),
  ('ruido', 'lawaai', 'noise'),
  ('sonido', 'geluid', 'sound'),
  ('señal', 'signaal', 'signal'),
  ('gesto', 'gebaar', 'gesture'),
  ('colegio', 'basisschool', 'primary school'),
  ('instituto', 'middelbare school', 'secondary school'),
  ('pizarra', 'schoolbord', 'blackboard'),
  ('asignatura', 'vak', 'subject'),
  ('matemáticas', 'wiskunde', 'mathematics'),
  ('geografía', 'aardrijkskunde', 'geography'),
  ('física', 'natuurkunde', 'physics'),
  ('química', 'scheikunde', 'chemistry'),
  ('biología', 'biologie', 'biology'),
  ('literatura', 'literatuur', 'literature'),
  ('filosofía', 'filosofie', 'philosophy'),
  ('diccionario', 'woordenboek', 'dictionary'),
  ('conocimiento', 'kennis', 'knowledge'),
  ('inteligencia', 'intelligentie', 'intelligence'),
  ('razón', 'rede', 'reason'),
  ('teoría', 'theorie', 'theory'),
  ('método', 'methode', 'method'),
  ('investigación', 'onderzoek', 'research'),
  ('invento', 'uitvinding', 'invention'),
  ('beca', 'beurs', 'scholarship'),
  ('tranvía', 'tram', 'tram'),
  ('helicóptero', 'helikopter', 'helicopter'),
  ('cohete', 'raket', 'rocket'),
  ('submarino', 'onderzeeër', 'submarine'),
  ('rueda', 'wiel', 'wheel'),
  ('volante', 'stuur', 'steering wheel'),
  ('freno', 'rem', 'brake'),
  ('motor', 'motor', 'engine'),
  ('faro', 'vuurtoren', 'lighthouse'),
  ('neumático', 'band', 'tyre'),
  ('casco', 'helm', 'helmet'),
  ('aparcamiento', 'parkeerplaats', 'parking'),
  ('atasco', 'file', 'traffic jam'),
  ('accidente', 'ongeluk', 'accident'),
  ('avería', 'pech', 'breakdown'),
  ('andén', 'perron', 'platform'),
  ('parada', 'halte', 'stop'),
  ('horario', 'dienstregeling', 'timetable'),
  ('retraso', 'vertraging', 'delay'),
  ('chaleco', 'vest', 'waistcoat'),
  ('sudadera', 'hoodie', 'hoodie'),
  ('blusa', 'blouse', 'blouse'),
  ('pañuelo', 'zakdoek', 'handkerchief'),
  ('bata', 'ochtendjas', 'dressing gown'),
  ('uniforme', 'uniform', 'uniform'),
  ('disfraz', 'kostuum', 'costume'),
  ('bolso', 'handtas', 'handbag'),
  ('cartera', 'portemonnee', 'wallet'),
  ('pulsera', 'armband', 'bracelet'),
  ('hilo', 'draad', 'thread'),
  ('aguja', 'naald', 'needle'),
  ('rechazar', 'weigeren', 'to reject'),
  ('aprobar', 'goedkeuren', 'to approve'),
  ('negar', 'ontkennen', 'to deny'),
  ('discutir', 'ruziën', 'to argue'),
  ('luchar', 'vechten', 'to fight'),
  ('atacar', 'aanvallen', 'to attack'),
  ('proteger', 'beschermen', 'to protect'),
  ('salvar', 'redden', 'to save'),
  ('curar', 'genezen', 'to cure'),
  ('matar', 'doden', 'to kill'),
  ('crecer', 'groeien', 'to grow'),
  ('mejorar', 'verbeteren', 'to improve'),
  ('aumentar', 'toenemen', 'to increase'),
  ('reducir', 'verminderen', 'to reduce'),
  ('saltar', 'springen', 'to jump'),
  ('empujar', 'duwen', 'to push'),
  ('tirar', 'trekken', 'to pull'),
  ('lanzar', 'gooien', 'to throw'),
  ('coger', 'pakken', 'to grab'),
  ('soltar', 'loslaten', 'to release'),
  ('apretar', 'knijpen', 'to squeeze'),
  ('atar', 'vastbinden', 'to tie'),
  ('doblar', 'vouwen', 'to fold'),
  ('girar', 'draaien', 'to turn'),
  ('colgar', 'ophangen', 'to hang'),
  ('pegar', 'plakken', 'to stick'),
  ('cortar', 'snijden', 'to cut'),
  ('quemar', 'branden', 'to burn'),
  ('hervir', 'koken', 'to boil'),
  ('freír', 'bakken', 'to fry'),
  ('mezclar', 'mengen', 'to mix'),
  ('pelar', 'schillen', 'to peel'),
  ('picar', 'hakken', 'to chop'),
  ('verter', 'gieten', 'to pour'),
  ('vaciar', 'legen', 'to empty'),
  ('secar', 'drogen', 'to dry'),
  ('mojar', 'nat maken', 'to wet'),
  ('barrer', 'vegen', 'to sweep'),
  ('coser', 'naaien', 'to sew'),
  ('cavar', 'graven', 'to dig'),
  ('plantar', 'planten', 'to plant'),
  ('regar', 'begieten', 'to water'),
  ('recoger', 'oprapen', 'to pick up'),
  ('sembrar', 'zaaien', 'to sow'),
  ('cazar', 'jagen', 'to hunt'),
  ('pescar', 'vissen', 'to fish'),
  ('ladrar', 'blaffen', 'to bark'),
  ('remar', 'roeien', 'to row'),
  ('navegar', 'varen', 'to sail'),
  ('bucear', 'duiken', 'to dive'),
  ('flotar', 'drijven', 'to float'),
  ('hundirse', 'zinken', 'to sink'),
  ('patinar', 'schaatsen', 'to skate'),
  ('escalar', 'klimmen', 'to climb'),
  ('pasear', 'wandelen', 'to stroll'),
  ('huir', 'vluchten', 'to flee'),
  ('escapar', 'ontsnappen', 'to escape'),
  ('perseguir', 'achtervolgen', 'to chase'),
  ('atrapar', 'vangen', 'to catch'),
  ('esconder', 'verstoppen', 'to hide'),
  ('señalar', 'wijzen', 'to point'),
  ('dibujar', 'tekenen', 'to draw'),
  ('borrar', 'wissen', 'to erase'),
  ('firmar', 'ondertekenen', 'to sign'),
  ('imprimir', 'printen', 'to print'),
  ('copiar', 'kopiëren', 'to copy'),
  ('calcular', 'berekenen', 'to calculate'),
  ('sumar', 'optellen', 'to add'),
  ('restar', 'aftrekken', 'to subtract'),
  ('medir', 'meten', 'to measure'),
  ('pesar', 'wegen', 'to weigh'),
  ('comparar', 'vergelijken', 'to compare'),
  ('ordenar', 'opruimen', 'to tidy'),
  ('organizar', 'organiseren', 'to organise'),
  ('planear', 'plannen', 'to plan'),
  ('escoger', 'kiezen', 'to choose'),
  ('preferir', 'verkiezen', 'to prefer'),
  ('dudar', 'twijfelen', 'to doubt'),
  ('adivinar', 'raden', 'to guess'),
  ('equivocarse', 'zich vergissen', 'to be wrong'),
  ('corregir', 'verbeteren', 'to correct'),
  ('comprobar', 'controleren', 'to check'),
  ('confirmar', 'bevestigen', 'to confirm'),
  ('prometer', 'beloven', 'to promise'),
  ('jurar', 'zweren', 'to swear'),
  ('engañar', 'bedriegen', 'to deceive'),
  ('confiar', 'vertrouwen', 'to trust'),
  ('sospechar', 'vermoeden', 'to suspect'),
  ('acusar', 'beschuldigen', 'to accuse'),
  ('perdonar', 'vergeven', 'to forgive'),
  ('agradecer', 'bedanken', 'to thank'),
  ('despedirse', 'afscheid nemen', 'to say goodbye'),
  ('presentar', 'voorstellen', 'to introduce'),
  ('visitar', 'bezoeken', 'to visit'),
  ('competir', 'wedijveren', 'to compete'),
  ('empatar', 'gelijkspelen', 'to draw'),
  ('rendirse', 'opgeven', 'to give up'),
  ('fracasar', 'mislukken', 'to fail'),
  ('brillar', 'schijnen', 'to shine'),
  ('enchufar', 'inpluggen', 'to plug in'),
  ('conectar', 'verbinden', 'to connect'),
  ('descargar', 'downloaden', 'to download'),
  ('instalar', 'installeren', 'to install'),
  ('actualizar', 'bijwerken', 'to update'),
  ('grabar', 'opnemen', 'to record'),
  ('compartir', 'delen', 'to share'),
  ('publicar', 'plaatsen', 'to post'),
  ('bloquear', 'blokkeren', 'to block'),
  ('profundo', 'diep', 'deep'),
  ('plano', 'plat', 'flat'),
  ('redondo', 'rond', 'round'),
  ('cuadrado', 'vierkant', 'square'),
  ('curvo', 'gebogen', 'curved'),
  ('agudo', 'scherp', 'sharp'),
  ('grueso', 'dik', 'thick'),
  ('fino', 'fijn', 'fine'),
  ('áspero', 'ruw', 'rough'),
  ('liso', 'glad', 'smooth'),
  ('transparente', 'doorzichtig', 'transparent'),
  ('templado', 'lauw', 'lukewarm'),
  ('maduro', 'rijp', 'ripe'),
  ('crudo', 'rauw', 'raw'),
  ('fresco', 'vers', 'fresh'),
  ('podrido', 'rot', 'rotten'),
  ('venenoso', 'giftig', 'poisonous'),
  ('ruidoso', 'luidruchtig', 'noisy'),
  ('silencioso', 'stil', 'quiet'),
  ('educado', 'beleefd', 'polite'),
  ('grosero', 'onbeleefd', 'rude'),
  ('generoso', 'gul', 'generous'),
  ('tacaño', 'gierig', 'stingy'),
  ('honesto', 'eerlijk', 'honest'),
  ('sincero', 'oprecht', 'sincere'),
  ('orgulloso', 'trots', 'proud'),
  ('humilde', 'nederig', 'humble'),
  ('egoísta', 'egoïstisch', 'selfish'),
  ('perezoso', 'lui', 'lazy'),
  ('inteligente', 'intelligent', 'intelligent'),
  ('estúpido', 'dom', 'stupid'),
  ('raro', 'zeldzaam', 'rare'),
  ('común', 'gewoon', 'common'),
  ('único', 'uniek', 'unique'),
  ('completo', 'volledig', 'complete'),
  ('entero', 'heel', 'whole'),
  ('medio', 'half', 'half'),
  ('doble', 'dubbel', 'double'),
  ('próximo', 'volgende', 'next'),
  ('anterior', 'vorige', 'previous'),
  ('docena', 'dozijn', 'dozen'),
  ('par', 'paar', 'pair'),
  ('mitad', 'helft', 'half'),
  ('década', 'decennium', 'decade'),
  ('temporada', 'seizoen', 'season'),
  ('festivo', 'feestdag', 'public holiday'),
  ('cumpleaños', 'verjaardag', 'birthday'),
  ('fiesta', 'feest', 'party'),
];
